### ISSUE TITLE
Dribbling run w/ bugfix

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#102]
### Description of the run

Identical to https://github.com/NCAR/amwg_dev/issues/91. Source code pointed to below has a bug fix. The nature of the fix is that the code was borrowed from an older version of E3SM that has a different definition of ```state%s``` (dse proper) than the current CAM code base (enthalpy=cpdry*T). So the dribbling tendency of s needed to be made consistent.

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Sandbox

Cecile it looks like you have your own checkout of my dribbling branch: /glade/work/hannay/cesm_tags/cam6_3_041.dribble

If you go into the code directory and type:
```
git fetch
git rebase
```
It should bring in the bug fix. These mod's impact physkg.F90, but I believe I put DQCORE into the branch so you shouldn't need to SourceMod anything in. Happy to double-check after you do the git commands.

### Contact info

@adamrher 
@JulioTBacmeister 

### Any other relevant information

@andrewgettelman - this means the dribbling code on our cam6_3_041.dtsens branch is buggy. Lets wait to see the results of this run before doing any dribbling expts.

**Comment by cecilehannay** [comment]
I didn't have any error when doing ``git fetch/git rebase``
Should I just checkout a new sandbox instead?

**Comment by cecilehannay** [comment]
Run started: #103
