### ISSUE TITLE
New topography file (with no "leaking" into ocean"

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/amwg_dev#116]
### Description of the run

We have produced a new topography file where we use a Laplacian smoother (instead of the default distance weighted smoother) and turn off smoothing where the land fraction is 0 (i.e. no smoothing over ocean points; partial ocean points are still smoothed). We are curious if not smoothing over ocean points has an impact in coupled model setup since the temperatures passed to the ocean, where previously the topography was "leaking into the ocean", could be biased cold (assuming temperature decreasing with height on average). 

The Figure below shows energy spectra for different topographies:

![Screen Shot 2022-05-16 at 9 44 07 AM](https://user-images.githubusercontent.com/8782989/168631954-68bb150e-0fe4-499a-a575-9b0a228fa6e6.png)

A couple of observations regarding the energy spectra:

- The energy spectra is the same when using a 3km intermediate cubed-sphere field (ncube3000, orange line) compared to using a 16km intermediate cubed-sphere grid (ncube540, red line) when computing energy spectra on 1 degree finite-volume grid. That means, we can assess smoothing using the ncube540 intermediate cubed-sphere grid which is much more computationally efficient to run the smoother on compared to the ncube3000 intermediate cubed-sphere grid.
- Interpolation matters for computing energy spectra: bi-linear interpolation from 1 degree spectral-element grid to 1 degree finite-volume grid produces damping (compare blue and red lines). Please note that the two grid "see" the exact same smoothed topography on the intermediate cubed-sphere grid. Hence when comparing different levels of smoothing always use the same target grid.
- The energy spectra with new and old smoother are very similar (compare red and green lines).
- Not smoothing over ocean does add some energy at many scales (compared cyan and red).
- Black line is unsmoothed topography (for reference)

The next two plots show Greenland area and South America topographies (all mapped to fv 1 degree grid):

-  ncube540 raw: raw topography on ~16km intermediate cubed-sphere (ncube540) 
- CESM2: Current default topography
- nc540: Laplacian smoothed topography (nu=28E7) - old CESM1.5 smoothing level when the SE topography was smoothed using SE (and not in the topography software as done now; which is needed for the ridge scheme variables)
- nc540;Co11: Laplacian smoothed topography (nu=20E7) that matches C011 smoothing (default CESM2) on the ncube540 grid (for the ncube3000 grid that is equivalent to C060 smoothing radius)
- nc540; no-ocn: Laplacian smoothed topography (nu=20E7) that matches C011 smoothing (default CESM2) but no smoothing over ocean.

The cross section plots (lower right) are though 30S and 65N.

![Screen Shot 2022-05-16 at 10 04 26 AM](https://user-images.githubusercontent.com/8782989/168635874-d7206810-23e8-4275-b6a8-c4697b8ad775.png)

![Screen Shot 2022-05-16 at 10 04 45 AM](https://user-images.githubusercontent.com/8782989/168635936-185ceb11-b052-4419-a092-055485263c93.png)

The following observations are made:

- Smoothing over peaks seems to be roughly the same for all smoothing options -> not smoothing over ocean does not seem to affect peaks a couple of grid-points inland.
- One can visually see no smoothing over ocean.

Global plot from @adamrher  showing difference between new PHIS minus the current namelists_defaults file:

![raster](https://user-images.githubusercontent.com/8782989/168639297-f11a09cf-c7b9-4011-b277-7566c3c88b49.png)

As expected lower topography near coastlines. However, another difference is the use of [bedmachine topography dataset](https://sites.uci.edu/morlighem/dataproducts/bedmachine-greenland/) so that added changes over Greenland.

Some mathematical details on the smoothing operator:

![Screen Shot 2022-05-16 at 10 35 07 AM](https://user-images.githubusercontent.com/8782989/168641094-ce62f143-063b-4a1d-95dd-40a8ac4f6fc7.png)

### Suffix in the casename

Suffix

### Namelist modifications

Please use settings from latest run coupled run except for new topo file in use_nl_cam:

bnd_topo = "/glade/p/cgd/amp/pel/topo/files/ne30pg3_gmted2010_bedmachine_nc3000_Laplace0100_20220516.nc"

### Source modifications

Please use all source code modifications from the latest coupled run (i.e. topo mods etc.)

### Sandbox

Please use code base from latest coupled run

### Contact info

@PeterHjortLauritzen 
@JulioTBacmeister 
@adamrher 

### Any other relevant information

Thank you!

**Comment by cecilehannay** [comment]
I am starting this run using the baseline: 
https://github.com/NCAR/amwg_dev/issues/112

This is the code we have been using for the coupled run.

**Comment by adamrher** [comment]
wondering if this thread should be xfer'd to https://github.com/NCAR/Topo issues ... or amwg_deg/discussions ...
it has a lot of good info to save, and these run requests are usually deleted to keep the issues in amwg_dev to the actual runs.

**Comment by cecilehannay** [comment]
The run requests are not deleted. They are just closed and still accessible. And there is also a link in the run itself. 

But I agree that there is plenty of great info in that thread. I was saying the same thing to Peter. It is a great idea to copy to the amwg_dev (I can do that) or to the Topo GitHub.

**Comment by cecilehannay** [comment]
Run started: #117

**Comment by JulioTBacmeister** [comment]
Were the odd diffs over the Himalayas resolved/understood

**Comment by PeterHjortLauritzen** [comment]
No. Will look at it ...
