### ISSUE TITLE
F-case control using cam6_3_058.dtsens

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#126]
### Description of the run

New f-case control using cam6_3_058.dtsens code base. Otherwise identical to prior controls.

### Suffix in the casename

Suffix

### Namelist modifications

```
./xmlchange CAM_CONFIG_OPTS='-phys cam_dev -nlev 58 -chem waccm_sc_mam4 -microphys mg2'
```

Note cam_dev will automatically invoke CAM6 microphysics. Pls use topo in https://github.com/NCAR/amwg_dev/issues/115.

We want to have extra aerosol output, I think that requires settting:

```
history_chemistry = .true.
history_chemspecies_srf = .true.
history_waccm = .true.
```
@tilmes is this what you meant by turning on aerosol diagnostics?

### Source modifications

I don't think any?

### Sandbox

cam6_3_058.dtsens

### Contact info

@adamrher 
@JulioTBacmeister 
@tilmes

**Comment by tilmes** [comment]
Hi Adam,
you want to set:
history_aerosol                =               .true.
to turn on the aerosol diagnostic output. 
I can also first check the CAM-chem simulation I have done with 58L and compare to a previous 32L run (I have not yet had time to do this). We could just run two specified dynamics runs, one with 32L and one with 58L and compare to see how the emissions change, then we could do another set of runs with the re-ordering change. That way we don't have to run 10+ years to compare the results?

**Comment by adamrher** [comment]
@tilmes @cecilehannay sounds good. We can hold off this 10 year run until we do some shorter SD expts. I actually have two separate solutions to this issue, so it would be good to test both. If I point you to some SourceMods later today, would you be able to do the runs?

**Comment by cecilehannay** [comment]
After talking to @Adam and @JulioTBacmeister, we will the new cesm sandbox for this run:
/glade/work/hannay/cesm_tags/cesm3_cam6_3_058_MOM
This includes Adam's branch. 

This run will use the topo file
```
bnd_topo = '/glade/p/cgd/amp/pel/topo/cesm3/ne30pg3_gmted2010_bedmachine_nc3000_Co060_20220427.nc'
```

**Comment by cecilehannay** [comment]
Run #132 completed.
