### ISSUE TITLE
F-case companion runs for 023 and 024.

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/amwg_dev#156]
### Description of the run

FHIST (1990-2000) experiments with exactly same settings and code as coupled experiments 023 and 024.  Purpose is to isolate cloud and radiative forcing changes due to physics using specified SSTs.

### Suffix in the casename

1) cam6_cice5.023
2) cam6_cice5.024

### Namelist modifications

Mirror namelists in corresponding coupled simulations.

### Sandbox

Requested sandbox or tag

### Contact info

@JulioTBacmeister 
@cecilehannay 
@dan800 (Dan Marsh)

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
@JulioTBacmeister:
These are running: #162 and #163

**Comment by dan800** [comment]
@JulioTBacmeister @cecilehannay A quick look indicates 024 has ~5% more low cloud than 023, reflecting more shortwave radiation and decreasing RESTOM by about 1.6W/m2.  RESTOM would generally be warming the planet (if it were interactive), so the rate of warming would be less. This is assuming I am reading the labels and signs correctly. It that your take?
