### ISSUE TITLE
023 + retuning

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/amwg_dev#159]
### Description of the run

Same as 023 + retuning to get RESTOM closer to zero.

Suggestions have been to use:
```
clubb_gamma_coef   =  0.28   (unchanged)
clubb_c14          = 2.2D0   (unchanged) 
clubb_c8= 4.2->4.4 
clubb_l_trapezoidal_rule_zm  =  .true. => .false.
clubb_l_trapezoidal_rule_zt  =  .true. => .false.
```

I also wonder if we want to start the ocean from the end of 023. That way the ocean would have run with a positive RESTOM for a couple of decades and it might help to start from a more spunup state. This is waht we observed in cesm2 development. But this might complicate the ocean comparison/analysis.

### Suffix in the casename

It will be run 024.

### Namelist modifications

```
clubb_gamma_coef   =  0.28   (unchanged)
clubb_c14          = 2.2D0   (unchanged) 
clubb_c8= 4.2->4.4 
clubb_l_trapezoidal_rule_zm  =  .true. => .false.
clubb_l_trapezoidal_rule_zt  =  .true. => .false.
```

### Source modifications

SourceMods from @PeterHjortLauritzen (bugfix in spectral-element advection) 

### Sandbox

Same as 023

### Contact info

@JulioTBacmeister, @adamrher, @gustavo-marques, @fobryan3 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
I just talked to Julio and we will separate the different tuning parameters in different runs. We will start with reverting the trapezoidal_rule in 024 and then add c8 tuning in 025.

**Comment by adamrher** [comment]
sounds good to me

**Comment by gustavo-marques** [comment]
Sounds good. Let's explore the effects of ocean/sea ice initialization in a separate simulation.

**Comment by cecilehannay** [comment]
Run 024 started (see: #161)
