### ISSUE TITLE
F-case with clubb_l_call_pdf_closure_twice set to .FALSE.

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/amwg_dev#170]
### Description of the run

FWscHIST compset run.

This run should be identical to #163 (f.024) except that we set namelist parameter
clubb_l_call_pdf_closure_twice		=  .false.

To complete testing of intertwined clubb pdf closure and trapezoidal rule behavior.  

With the settings in this configuration, pdf closure will only be performed at model mid-layers, not both at mid-layers and layer-edges.  Trapezoidal rule is therefore not needed to reconstruct consistent layer mean values from mid-layer and edge values of q T etc. 

### Suffix in the casename

025 (?)

### Namelist modifications

clubb_l_call_pdf_closure_twice		=  .false.

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@adamrher , @JulioTBacmeister , @ce

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
Run started as: 
https://github.com/NCAR/amwg_dev/issues/171
