### ISSUE TITLE
Start a run 26c with spunup land ic 

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/amwg_dev#184]
### Description of the run

We  planning to start a new cesm simulation with a spunup land ic. Basically, it will be similar 26a + land ic from 016 at year 58.

The restart files are: /glade/p/cesmdata/cseg/inputdata/cesm2_init/b.cesm3_cam058_mom_e.B1850MOM.f09_L32_t061.cam6_cice5.016/0058-01-01

@brianpm is going to look at the ic condition before we start the run. @olyson and @wwieder are welcome to look it too. 
@klindsay28 is going to provide a file + bugfix for ocean diags

Please let us know if there is any show stopper.

### Suffix in the casename

26c

### Namelist modifications

same as 26a + file from Keith L

### Source modifications

same as 26a + file from Keith L

### Sandbox

Same as 26a

### Contact info

@JulioTBacmeister and @cecilehannay 

### Any other relevant information

None

**Comment by klindsay28** [comment]
Please copy `diag_table` and `MOM_tracer_registry.F90` from `/glade/work/klindsay/cesm23_cases/BMOM/b.cesm3_cam058_mom_e.B1850WscMOM.ne30_L32_t061.camdev_cice5.022.clone/SourceMods/src.mom` to `SourceMods/src.mom`, replacing `b.cesm3_cam058_mom_e.B1850WscMOM.ne30_L32_t061.camdev_cice5.022.clone` in `diag_table` with the name of your new case.
`diag_table` adds tracer and thickness budget diagnostic terms.
`MOM_tracer_registry.F90` corrects a bug in one of the added diagnostics.

**Comment by klindsay28** [comment]
Do you want to include the fix for the [exact restart bug](https://github.com/ESCOMP/CAM/issues/655)?

I copied the fix that @bstephens82 developed to `/glade/work/klindsay/cesm23_cases/BMOM/b.cesm3_cam058_mom_e.B1850WscMOM.ne30_L32_t061.camdev_cice5.022.clone/SourceMods/src.cam/radiation.F90`.

**Comment by adamrher** [comment]
@cecilehannay did you re-checkout my cam branch? I sent you an email saying that this cam_dev restart bug fix has been implemented on my branch.

**Comment by cecilehannay** [comment]
No, I have been using the same code base. I don't really want to change the sandbox. I prefer to include SourceMods. When we are ready to move sandbox, I will do that. 


Right now, I just include: /glade/p/cesmdata/cseg/runs/cesm2_0/b.cesm3_cam058_mom_e.B1850WscMOM.ne30_L58_t061.camdev_cice5.026c/SourceMods/src.cam/radiation.F90

**Comment by adamrher** [comment]
fine by me

**Comment by brianpm** [comment]
I took a look at `/glade/p/cesmdata/cseg/inputdata/lnd/clm2/initdata_map/clmi.B1850Clm50BgcCrop.0161-01-01.0.9x1.25_gx1v7_simyr1850_c200729.nc`. I don't know how to get a decent looking plot of `SNOW_DEPTH(column)` (I guess using `cols1d_lat` and `cols1d_lon` as coordinates). It does seem to have a lot of points >10m. Here's the distribution:

![image](https://user-images.githubusercontent.com/5471157/193363575-b6a77ee3-75c2-458e-becb-fcfac504c54f.png)


That pretty much confirms, I think, that it isn't a problem in going from the IC file to the model grid.

**Comment by olyson** [comment]
Thanks Brian, here is:
Snow depth on vegetated column in 016 land restart file at year 58:
![b cesm3_cam058_mom_e B1850MOM f09_L32_t061 cam6_cice5 016 clm2 r 0058-01-01-00000 SNOW_DEPTH](https://user-images.githubusercontent.com/18671367/193358897-459cd104-cb66-4f4e-b9c5-10f4139fe094.png)

Same but in land restart file being used for these coupled simulations thus far:

![clmi B1850Clm50BgcCrop 0161-01-01 0 9x1 25_gx1v7_simyr1850_c200729 SNOW_DEPTH](https://user-images.githubusercontent.com/18671367/193358928-169866a0-f483-45fd-9e7a-1c7aad27922a.png)

**Comment by cecilehannay** [comment]
Run started (see #185)
