### ISSUE TITLE
Two FHIST with/without non-orographic GW schemes

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/amwg_dev#189]
### Description of the run

Start 2 runs:
- one with non-orographic GW schemes
- one without non-orographic GW schemes

### Namelist modifications

Request from Simone: Include history_aerosol

### Source modifications

will depend on code base

### Sandbox

Which code base should we use? 
- 26d? 
- Or more recent version including PUMAS?

### Contact info

@JulioTBacmeister, @dan800, @tilmes

**Comment by adamrher** [comment]
no to 26d -- the runoff fluxes and subsequent corrections are not physical. suggest to start with 26c.

**Comment by cecilehannay** [comment]
Sorry, I meant 26c and not 26d. 

The question was whether we want to start these runs with
- the same code as in 26c 
- or a new version of the code that includes PUMAS. 

We started to discuss this during the CAM7 meeting but then we decided to postpone the discussion.

Personally, I would have done this with the current code (26c) so we don't change several things at the same time. But I am fine either way.

**Comment by adamrher** [comment]
I vote for 26c for this sensitivity experiment.

Can what "on" means ... to turn "on" non-orographic GW means to turn on both frontal AND convective GW schemes?

**Comment by tilmes** [comment]
I would vote for the latest version so we are up to date.
Once this is tested and looks OK, I will also do a Chemistry run,
Thanks Simone

**Comment by JulioTBacmeister** [comment]
I am not convinced the GW sensitivity experiments need to be coupled runs.
I would advocate for F-cases for these.

**Comment by cecilehannay** [comment]
@JulioTBacmeister
To clarify: you are correct, we are planning to do F cases (or more exactly FWscHIST). 
When we said the configuration of 26c, we meant we wanted to use the tuning from 26c in a F case.

**Comment by tilmes** [comment]
@cecilehannay I am really fine whatever version you think is best, for this test we only need to compare the 2 cases. Doing the previous case may be useful, if you add the aerosol diagnostics, we could have a look how they perform at this point.

**Comment by JulioTBacmeister** [comment]
Yes. Let's start a pair of L58 F-case runs using the 26c configuration: a) without non-orographic GWs; and b) with non-orographic GWs.  One or both can run with aerosol diagnostics on.  I any case, I don't expect the non-orographic GW settings will have much impact on anything besides lower stratospheric dynamics. 

The intent here is simply to see whether L58 with SE-dycore produces _anything_ at all in terms of a "vacillation" in the equatorial lower stratosphere.  Namelist settings are given in the run description above.

**Comment by cecilehannay** [comment]
Run #191 and #190
