### ISSUE TITLE
corrected topo file L93

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/amwg_dev#207]
### Description of the run

Repeat #204 with corrected topo file

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

Contact information
juliob@ucar.edu
### Any other relevant information

Enter relevant info

**Comment by JulioTBacmeister** [comment]
use 
/glade/p/cgd/amp/juliob/bndtopo/latest/ne30pg3_gmted2010_modis_bedmachine_nc3000_Laplace0100_20230105.nc

**Comment by cecilehannay** [comment]
Run is started (see: #210)
