### ISSUE TITLE
new baseline with cam6_3_100

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/amwg_dev#223]
### Description of the run

@adamrher , @JulioTBacmeister  and @PeterHjortLauritzen  would like a new baseline created with cam6_3_100 (FWscHIST, L58) in preparation for evaluating new science code (incl. condensates in pressure and having energy fixer use an energy consistent with the dynamical core).

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

Contact information@adamrher , @JulioTBacmeister  and @PeterHjortLauritzen 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
After talking to @JulioTBacmeister and @PeterHjortLauritzen, we are planning @bstephens82's latest tuning and thomas's bug fix:  to this run



Bug fix sourcemod location: ```/glade/u/home/stepheba/cam92/cime/scripts/d92pmf_c7_0.4_5yrs/SourceMods/src.cam/mono_flux_limiter.F90```
```
clubb_l_predict_upwp_vpwp=.true.  ! turns on prognostic momentum fluxes
clubb_l_mono_flux_lim_um   = .true.    ! necessary if using l_predict_upwp_vpwp=T
clubb_l_mono_flux_lim_vm   = .true.    ! ditto

clubb_c7=0.4
clubb_c_uu_shr = 0.1
```

Any objections?

**Comment by bstephens82** [comment]
> After talking to @JulioTBacmeister and @PeterHjortLauritzen, we are planning @bstephens82's latest tuning and thomas's bug fix (@tto061) to this run
> 
> Bug fix sourcemod location: `/glade/u/home/stepheba/cam92/cime/scripts/d92pmf_c7_0.4_5yrs/SourceMods/src.cam/mono_flux_limiter.F90`
> 
> ```
> clubb_l_predict_upwp_vpwp=.true.  ! turns on prognostic momentum fluxes
> clubb_l_mono_flux_lim_um   = .true.    ! necessary if using l_predict_upwp_vpwp=T
> clubb_l_mono_flux_lim_vm   = .true.    ! ditto
> 
> clubb_c7=0.4
> clubb_c_uu_shr = 0.1
> ```
> 
> Any objections?

I am still waiting on some 30-year runs to complete, but at this point I would say that, with the bug fix, a smaller value of C7 might be better, maybe 0.1 or 0.2 which are the values I'm currently testing.  C7=0.1 seems to give a better surface stress field, but PSL seems slightly better with C7=0.2.  Then again, if PSL takes a long time to stabilize, then C7=0.1 might be the better choice?

**Comment by cecilehannay** [comment]
Do we want to wait until your run completes to start this one?

**Comment by bstephens82** [comment]
> are we still investigating predict_upwp=T and mfl for um/vm=F?

I have a test going for this setup.

**Comment by adamrher** [comment]
@tilmes care to chime in? 

@cecilehannay can we also make sure the aerosol output is on for aerosol diagnostics?

**Comment by tilmes** [comment]
I gave these values to Cecile, but things have changed, so we need to check again after the run.
You just need to add the aerosol history namelist variable, but even without, I think, we can look at AODDUST and AODVIS, if you have that.

**Comment by adamrher** [comment]
For reference, here's the out of the box values used in the 26 series:
```
 dust_emis_fact         = 0.8D0
 seasalt_emis_scale             = 1.00D0
```

The nl ```lght_no_prd_factor``` is not in atm_in in our 26 series runs ... is this feature only on for CAM-CHEM compsets?

**Comment by tilmes** [comment]
@adamrher if you run with dust_emis_fact = 0.8D0 we may want to actually keep that, because the dust was already low and increasing the dust factor would make it even lower.

**Comment by bstephens82** [comment]
> @JulioTBacmeister says: Let's wait.

The 30-year runs finally finished today.  Here are the diagnostics.  The only difference between these two runs is the value of clubb_c7, which is either 0.1 or 0.2.

clubb_c7=0.1:
https://webext.cgd.ucar.edu/F2000climo/d92pmf_c7_0.1_5yrs/atm/d92pmf_c7_0.1_5yrs-obs.0001_30/

clubb_c7=0.2:
https://webext.cgd.ucar.edu/F2000climo/d92pmf_c7_0.2_5yrs/atm/d92pmf_c7_0.2_5yrs-obs.0001_30/

Apologies for the "5yrs" in the naming which is confusing.  I started them as 5yr runs and then extended them.

**Comment by adamrher** [comment]
> although it looks like clubb_c7=0.1 gives a very slightly better surface stress bias?

marginally better over the Southern Ocean for [0.1](https://webext.cgd.ucar.edu/F2000climo/d92pmf_c7_0.1_5yrs/atm/d92pmf_c7_0.1_5yrs-obs.0001_30/set5_6/set6_ANN_STRESS_LARYEA_obsc.png) compared to [0.2](https://webext.cgd.ucar.edu/F2000climo/d92pmf_c7_0.2_5yrs/atm/d92pmf_c7_0.2_5yrs-obs.0001_30/set5_6/set6_ANN_STRESS_LARYEA_obsc.png).

**Comment by tilmes** [comment]
SWCF over the Southern Ocean could be also changed by tuning sea-salt emissions.
If you point me to your climo files, I can look at AOD from observations for that as well to see if we are high or low compared to the data.

**Comment by adamrher** [comment]
@bstephens82 I personally don't think we should commit the c8 or gamma changes you tested over the last several days, as we are also exploring reducing salt emissions to resolve some cloud biases ... and I suspect we'll be iterating over the next several days before we have some concrete rec'd ... and I don't think it's worth holding up the new baseline.

**Comment by cecilehannay** [comment]
To clarify: we were not planning to commit anything to the trunk at this point. However, Julio suggested some changes to the clubb parameters that he deemed robust, and he suggested using them for the new baseline.

**Comment by adamrher** [comment]
We don't have robust cloud tunings yet. I think we should just run this out of the box if one the main points is to understand peter's energy changes.

We can wait until @bstephens82 chimes in to confirm. Julio could be referring to PMF. But I'm not sure whether we should turn that on for this baseline.

**Comment by cecilehannay** [comment]
Thanks @adamrher. I am not sure the changes @JulioTBacmeister was referring to (he just said some clubb tunings) but I will wait to hear from @bstephens82.

**Comment by bstephens82** [comment]
> After talking to @JulioTBacmeister and @PeterHjortLauritzen, we are planning @bstephens82's latest tuning and thomas's bug fix (@tto061)  to this run
> 
> 
> 
> 
> 
> 
> 
> Bug fix sourcemod location: ```/glade/u/home/stepheba/cam92/cime/scripts/d92pmf_c7_0.4_5yrs/SourceMods/src.cam/mono_flux_limiter.F90```
> 
> ```
> 
> clubb_l_predict_upwp_vpwp=.true.  ! turns on prognostic momentum fluxes
> 
> clubb_l_mono_flux_lim_um   = .true.    ! necessary if using l_predict_upwp_vpwp=T
> 
> clubb_l_mono_flux_lim_vm   = .true.    ! ditto
> 
> 
> 
> clubb_c7=0.4
> 
> clubb_c_uu_shr = 0.1
> 
> ```
> 
> 
> 
> Any objections? 

Hi Cecile, based on our latest tests, the only change to make to this setup is to set clubb_c7=0.1.

**Comment by cecilehannay** [comment]
To verify: do we want to use ``clubb_l_predict_upwp_vpwp=.true.`` for this run. 
I know  @bstephens82 just said in the previous message. 
However, I have receiving conflicting info on that run because things are changing so far. It is why I want to make sure we have the green light from all the concerned parties.

**Comment by bstephens82** [comment]
> To verify: do we want to use ``clubb_l_predict_upwp_vpwp=.true.`` for this run. 
> 
> I know  @bstephens82 just said in the previous message. 
> 
> However, I have receiving conflicting info on that run because things are changing so far. It is why I want to make sure we have the green light from all the concerned parties. 
> 
> 

My understanding is yes, since the values of c_uu_shr and c7 I suggested are based on prognostic momentum fluxes being turned on (along with the MFL for um and vm, with the big fix).

**Comment by adamrher** [comment]
Yes, it seems we want to be running with PMF, using Ben's rec'd namelists and SourceMod. It makes sense to move forward with PMF as a baseline now.

**Comment by cecilehannay** [comment]
Perfect. I will run with Ben's changes

**Comment by cecilehannay** [comment]
The case directory is here: ``/glade/p/cesmdata/cseg/runs/cesm2_0/f.cam6_3_100.FWscHIST.ne30_L58.001``

Please feel free to have a look before we start the run.

**Comment by PeterHjortLauritzen** [comment]
No need for extensive dycore energy diagnostics for this run, i.e. please replace 

'WV_phBF:A','WL_phBF:A','WI_phBF:A','SE_phBF:A','KE_phBF:A',
'WV_phBP:A','WL_phBP:A','WI_phBP:A','SE_phBP:A','KE_phBP:A',
'WV_phAP:A','WL_phAP:A','WI_phAP:A','SE_phAP:A','KE_phAP:A',
'WV_phAM:A','WL_phAM:A','WI_phAM:A','SE_phAM:A','KE_phAM:A',
'WV_dyBF:A','WL_dyBF:A','WI_dyBF:A','SE_dyBF:A','KE_dyBF:A',
'WV_dyBP:A','WL_dyBP:A','WI_dyBP:A','SE_dyBP:A','KE_dyBP:A',
'WV_dyAP:A','WL_dyAP:A','WI_dyAP:A','SE_dyAP:A','KE_dyAP:A',
'WV_dyAM:A','WL_dyAM:A','WI_dyAM:A','SE_dyAM:A','KE_dyAM:A',
'WV_dBF:A','WL_dBF:A','WI_dBF:A','SE_dBF:A','KE_dBF:A',
'WV_dED:A','WL_dED:A','WI_dED:A','SE_dED:A','KE_dED:A',
'WV_dAD:A','WL_dAD:A','WI_dAD:A','SE_dAD:A','KE_dAD:A',
'WV_dAF:A','WL_dAF:A','WI_dAF:A','SE_dAF:A','KE_dAF:A',
'WV_dBD:A','WL_dBD:A','WI_dBD:A','SE_dBD:A','KE_dBD:A',
'WV_dAR:A','WL_dAR:A','WI_dAR:A','SE_dAR:A','KE_dAR:A',
'WV_dAH:A','WL_dAH:A','WI_dAH:A','SE_dAH:A','KE_dAH:A',
'WV_dBH:A','WL_dBH:A','WI_dBH:A','SE_dBH:A','KE_dBH:A',
'WV_dCH:A','WL_dCH:A','WI_dCH:A','SE_dCH:A','KE_dCH:A',
'WV_dAS:A','WL_dAS:A','WI_dAS:A','SE_dAS:A','KE_dAS:A',
'WV_dBS:A','WL_dBS:A','WI_dBS:A','SE_dBS:A','KE_dBS:A'

with 

'WV_phBF:A','WL_phBF:A','WI_phBF:A','SE_phBF:A','KE_phBF:A',
'WV_phBP:A','WL_phBP:A','WI_phBP:A','SE_phBP:A','KE_phBP:A',
'WV_phAP:A','WL_phAP:A','WI_phAP:A','SE_phAP:A','KE_phAP:A',
'WV_phAM:A','WL_phAM:A','WI_phAM:A','SE_phAM:A','KE_phAM:A'

in user_nl_cam. 

Thanks

**Comment by cecilehannay** [comment]
Done.

**Comment by cecilehannay** [comment]
Hi @bstephens82,
I set:
```
clubb_c7                = 0.1
```

Please could you confirm that you only want to change ``clubb_c7`` and not ``clubb_c7b``

Right now, I have:
```
clubb_c7                = 0.1
clubb_c7b               = 0.5    
```
I think this is what you want, but just to confirm.

**Comment by cecilehannay** [comment]
Run set as: https://github.com/NCAR/amwg_dev/issues/227
