### ISSUE TITLE
run with energy mods (based on cam6_3_100)

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/amwg_dev#224]
### Description of the run

Science evaluate "new energy" code (incl. condensates in pressure and having energy fixer use an energy consistent with the dynamical core) and compare to cam6_3_100 baseline (issue #223)

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

https://github.com/jtruesdal/CAM-1

branch: ebudget_dev_update

tag will be provided once we are ready for simulation
```
git clone https://github.com/jtruesdal/CAM-1.git cam6_3_100_ebudget_dev_update
cd cam6_3_100_ebudget_dev_update
git checkout ebudget_dev_update
./manage_externals/checkout_externals
```
### Contact info

pel@ucar.edu

### Any other relevant information

The budgeting works like the amwg diagnostics but writes energy budgets variables to a history file. You can not specify empty_htapes when you are requesting a budget history tape. To turn on budgeting you need to enable it by setting thermo_budget_history to .true. and then pick an unused history tape number for the budget output and set thermo_budget_histfile_num to that.  I would recommend the next history file in the list after what is already being used.  Set the frequency over which the budget will be calculated using the nhtfrq namelist parameter for the budget history file number. Lastly the budget history files have a special averaging flag so you need to set the avgflag_pertape to 'N' for the history budget tape.  Here are the steps to make a monthly budget using history file 4.
```
1) Do not call empty_htapes
2) thermo_budget_history = .true.
3) thermo_budget_histfile_num = 4
4) avgflag_pertape(4) = 'N'
5) nhtfrq(4) = 0
```

**Comment by cecilehannay** [comment]
@PeterHjortLauritzen and @jtruesdal: the control for this run is crashing after a few years. Do we want to start this run anyway or wait until we understand the crash in the control.

**Comment by cecilehannay** [comment]
I am closing this issue as we are running: https://github.com/NCAR/amwg_dev/issues/228
