### ISSUE TITLE
Run to test new compset: FLTHIST_v0a (f.FLTHIST_v0a.ne30_L58.001)

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/amwg_dev#226]
### Description of the run

The purpose of this run will be to test the new compset ``FLTHIST_v0a`` (this compset is the first version of ``FLTHIST``). 

### Suffix in the casename

None

### Namelist modifications

None

### Source modifications

None

### Sandbox

Cheryl sandbox = cam6_3_101 

### Contact info

@cacraigucar, @cecilehannay, @julio, @fvitt

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
Thanks, @fvitt

**Comment by cecilehannay** [comment]
Hi @fvitt, @tilmes, @dan800

We created a case directory 
```
/glade/p/cesmdata/cseg/runs/cesm2_0/f.FLTHIST_v0a.ne30_L58.001
```
with the new compset 
```FLTHIST_v0a``` 

The code we used is: 
```
https://github.com/cacraigucar/CAM 
git checkout cam_compsets
```

We updated some of the namelist settings to match with what we got with FWscHIST. For that purpose, @brian-eaton created the new use case: ``hist_cam_lt.xml``
Before starting a test run, we would like to make sure the namelist settings are what you want for this new compset (ozone, flbc, ...).  

Please could you review the namelist 
```/glade/p/cesmdata/cseg/runs/cesm2_0/f.FLTHIST_v0a.ne30_L58.001/CaseDocs/atm_in```
and make it matches for you want for this compset. 

Please let us know any changes. Thanks.

**Comment by cecilehannay** [comment]
@dan800: don't worry about the casename. The name won't have L58 in it. This is not the final case directory that we will run. This is just create for you to review the namelists.

**Comment by fvitt** [comment]
@jedwards4b This question is what happens in the cam history code?

**Comment by jedwards4b** [comment]
I believe that empty_htapes just removes the defaults and anything explicitly added in the atm_in will be written.

**Comment by brian-eaton** [comment]
@fvitt, I agree with @jedwards4b.  The `history_aerosol` flag is used in the init methods to add default fields to specified history files.  When the final field lists for each output history file are assembled the fields listed in `fincl` variables are always included, and the default fields are only included if `empty_htapes` is false or if they haven't been specifically excluded by a `fexcl` variable.

**Comment by cecilehannay** [comment]
The reason we do 
```
 empty_htapes = .true.
```
in these development simulations is that we don't want to generate a lot of output people don't look at, so we select the output we want to look in the ``fincl``.

The reason we do 
```
 history_aerosol = .true.
```
is that Simone wants these in these development simulations.

**Comment by fvitt** [comment]
> @fvitt, I agree with @jedwards4b. The `history_aerosol` flag is used in the init methods to add default fields to specified history files. When the final field lists for each output history file are assembled the fields listed in `fincl` variables are always included, and the default fields are only included if `empty_htapes` is false or if they haven't been specifically excluded by a `fexcl` variable.

@brian-eaton Cicile has set `empty_htapes = .true.` and `history_aerosol = .true.`. So in this case, it seems to me that the defaults added by `history_aerosol`  would not be included in the output.  Am I confused?

**Comment by tilmes** [comment]
@cecilehannay if you did not  include  the aerosol fields for now, that is OK, as long as we have AOD, we can look at the effects of aerosol.

**Comment by brian-eaton** [comment]
@fvitt, I spent an hour looking at cam history code and I believe that if `empty_htapes=.true.` then `history_aerosol=.true.` will have no effect on the output files.  It adds "default" fields, but these are not output when `empty_htapes=.true.`.  This agrees with what Jim said originally.

**Comment by cecilehannay** [comment]
@tilmes: look at brian's comment above: it sounds like that because we use the flag ``empty_htapes=.true.`` then ``history_aerosol=.true.`` will have no effect. 

As we want to use ``empty_htapes=.true.`` at the moment, you need to tell me the specific variables you want to output. I am sorry about that, but if you give me your specific variables, I am more than happy to add them to my fincl. 

Thanks

**Comment by adamrher** [comment]
All, this statement from Jim: 

> I believe that empty_htapes just removes the defaults and anything explicitly added in the atm_in will be written.

is correct. That is, if empty_tapes=F and history_aerosol=T, aerosols will still be written to history ... can someone just try this so we don't have to pontificate over the code?!

**Comment by fvitt** [comment]
@cecilehannay Since you are using cam_dev phys you will need to remove the TEM diags stuff.  Otherwise, the things I am familiar with look okay to me.

**Comment by tilmes** [comment]
@cecilehannay Regarding output, I assume you have AODVISdn? If not that would be really helpful.
I can send you the entire list of the aerosols for calculating the budgets:
'AODVISdn', 'AQSO4_H2O2','AQSO4_O3',
         'bc_a1', 'bc_a4', 'dst_a1', 'dst_a2', 'dst_a3', 'ncl_a1',
         'ncl_a1', 'ncl_a2', 'ncl_a3', 'pom_a1', 'pom_a4', 'so4_a1', 'so4_a2', 'so4_a3',
         'soa_a1', 'soa_a2', 'bc_c1', 'bc_c4', 'dst_c1', 'dst_c2', 'dst_c3', 'ncl_c1',
         'ncl_c1', 'ncl_c2', 'ncl_c3', 'pom_c1', 'pom_c4', 'so4_c1', 'so4_c2', 'so4_c3',
         'soa_c1', 'soa_c2', 'num_a1', 'num_a2', 'num_a3', 'num_a4', 'num_c1', 'num_c2',
         'num_c3', 'num_c4', 'bc_a1SFWET', 'bc_a4SFWET', 'dst_a1SFWET', 'dst_a2SFWET', 'dst_a3SFWET', 'ncl_a1SFWET',
         'ncl_a2SFWET', 'ncl_a3SFWET', 'pom_a1SFWET', 'pom_a4SFWET', 'so4_a1SFWET', 'so4_a2SFWET', 'so4_a3SFWET', 'soa_a1SFWET',
         'soa_a2SFWET', 'bc_c1SFWET', 'bc_c4SFWET', 'dst_c1SFWET', 'dst_c2SFWET', 'dst_c3SFWET', 'ncl_c1SFWET', 'ncl_c2SFWET',
         'ncl_c3SFWET', 'pom_c1SFWET', 'pom_c4SFWET', 'so4_c1SFWET', 'so4_c2SFWET', 'so4_c3SFWET', 'soa_c1SFWET', 'soa_c2SFWET',
         'bc_a1DDF', 'bc_a4DDF', 'dst_a1DDF', 'dst_a2DDF', 'dst_a3DDF', 'ncl_a1DDF', 'ncl_a2DDF', 'ncl_a3DDF',
         'pom_a1DDF', 'pom_a4DDF', 'so4_a1DDF', 'so4_a2DDF', 'so4_a3DDF', 'soa_a1DDF', 'soa_a2DDF', 'bc_c1DDF',
         'bc_c4DDF', 'dst_c1DDF', 'dst_c2DDF', 'dst_c3DDF', 'ncl_c1DDF', 'ncl_c2DDF', 'ncl_c3DDF', 'pom_c1DDF',
         'pom_c4DDF', 'so4_c1DDF', 'so4_c2DDF', 'so4_c3DDF', 'soa_c1DDF', 'soa_c2DDF',
         'num_a1DDF', 'num_a2DDF',
         'num_a3DDF', 'num_a4DDF', 'num_c1DDF', 'num_c2DDF', 'num_c3DDF', 'num_c4DDF', 'bc_a4_CLXF', 'pom_a4_CLXF',
         'so4_a1_CLXF', 'so4_a2_CLXF', 'num_a1_CLXF', 'num_a2_CLXF', 'SFbc_a4', 'SFpom_a4', 'SFso4_a1', 'SFso4_a2',
         'SFnum_a1', 'SFnum_a2', 'SFnum_a3', 'so4_a1_sfgaex1', 'so4_a2_sfgaex1', 'so4_a3_sfgaex1', 'soa_a1_sfgaex1', 'soa_a2_sfgaex1',
         'so4_a2_sfnnuc1', 'so4_c1AQH2SO4', 'so4_c2AQH2SO4', 'so4_c3AQH2SO4', 'so4_c1AQSO4', 'so4_c2AQSO4', 'so4_c3AQSO4', 'SFdst_a1',
         'SFdst_a2', 'SFdst_a3', 'SFncl_a1', 'SFncl_a2', 'SFncl_a3', 'soa_a1_CHML', 'soa_a1_CHML', 'so4_a1_CHMP',
         'so4_a2_CHMP', 'so4_a3_CHMP', 'soa_a1_CHMP', 'soa_a1_CHMP', 'H2SO4_sfnnuc1',
         'num_a2_sfnnuc1'

**Comment by cecilehannay** [comment]
@tilmes: Do you need the fill list in every run? Depending on whether these variables are 2D or 3D, the list could become quite large. Alternatively, I could output the list periodically instead.

**Comment by tilmes** [comment]
yes, if it is possible output periodically that would be enough, or we could also repeat the a year at  one point with the whole list.

**Comment by dan800** [comment]
@tilmes Can you describe the budgets you mention? I don't expect for tuning all these individual species or rates are needed for every run. I wonder if they be calculated in-line by the model by either: 1) defining chemical families in the namelist and outputing those, 2) saving combined rates (possible from the namelist?) or 3) writing the budget calculation inline in the code and saving only the budget diagnostic.

**Comment by dan800** [comment]
> The purpose of this run will be to test the new compset `FLTHIST_v0a`



> @cecilehannay , This is for a 1-degree horizontal grid with TEM diags calculated and output every 6 hours:
> 
> ```
> phys_grid_ctem_nfreq=-6
> phys_grid_ctem_zm_nbas=120
> phys_grid_ctem_za_nlat=90
> fincl2 = 'VTHzaphys','WTHzaphys','UVzaphys','UWzaphys'
> nhtfrq = 0,-6
> ...
> ```
> 
> I am not sure how frequent you need the TEM diags.

The calculation needs to be done every 6 hours but accumlated into monthly means do I think this should be nhtfrq=0,0

Please try to get the code in to get the TEM working - if I read this correctly, the TEM code does not work in this tag.

**Comment by tilmes** [comment]
@dan800 The variables are needed to calculate the aerosol budget: emissions, productions, loss, lifetime. We do not need the output for every run, but we have changed a lot of things recently  in terms of aerosols and it may be useful to make sure we don't see any surprises. As I suggested,  we can save those outputs just for a year or two, and that would be OK.

**Comment by fvitt** [comment]
> > The purpose of this run will be to test the new compset `FLTHIST_v0a`
> 
> > @cecilehannay , This is for a 1-degree horizontal grid with TEM diags calculated and output every 6 hours:
> > ```
> > phys_grid_ctem_nfreq=-6
> > phys_grid_ctem_zm_nbas=120
> > phys_grid_ctem_za_nlat=90
> > fincl2 = 'VTHzaphys','WTHzaphys','UVzaphys','UWzaphys'
> > nhtfrq = 0,-6
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am not sure how frequent you need the TEM diags.
> 
> The calculation needs to be done every 6 hours but accumlated into monthly means, so I think this should be nhtfrq=0,0
> 
> Please try to get the code in to get the TEM working - if I read this correctly, the TEM code does not work in this tag.

@dan800, The fix is in this PR:
https://github.com/ESCOMP/CAM/pull/770

**Comment by cecilehannay** [comment]
Run start as: https://github.com/NCAR/amwg_dev/issues/229
