### ISSUE TITLE
Control with 102 with TEM diags

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/amwg_dev#233]
### Description of the run

We are starting a new run with 102 that will include:
- CO2 fix (as in #232) 
- TEM diags

### Suffix in the casename

Suffix

### Namelist modifications

Namelist same as in #232 plus"
```
fincl5 = 'VTHzaphys','WTHzaphys','UVzaphys','UWzaphys','Uzm', 'Wzm', 'Vzm', 'THzm'
phys_grid_ctem_nfreq=-6
phys_grid_ctem_zm_nbas=120
phys_grid_ctem_za_nlat=90
```

@fvitt and @islasimpson: please confirm the setting.  

### Source modifications

SourceMods: CO2, COSP  

### Sandbox

cam6_3_102

### Contact info

@cacraigucar, @cecilehannay, @julio, @fvitt, @adamrher, @brianpm, @dan800, @klindsay28, @islasimpson

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
@PeterHjortLauritzen and @jtruesdal: any output you want in case we use 102 as the new baseline for testing the new energy code.

**Comment by dan800** [comment]
@cecilehannay #232 has:
mfilt           = 0,5,20,40,120,240,365,73,365
nhtfrq         =                  0, -24,  -6,  -3,  -6,   1, -24,-24
We want the TEM output (fincl5) to be monthly. I'd put 12 months in a single file to make it easy - they're only zm fields, so small output.

**Comment by PeterHjortLauritzen** [comment]
Monthly averaged:

finclX =   'WV_phBF','WL_phBF','WI_phBF','SE_phBF','KE_phBF', 
               'WV_phBP','WL_phBP','WI_phBP','SE_phBP','KE_phBP',
              'WV_phAP','WL_phAP','WI_phAP','SE_phAP','KE_phAP',
              'WV_phAM','WL_phAM','WI_phAM','SE_phAM','KE_phAM',
        'WV_dyBF','WL_dyBF','WI_dyBF','SE_dyBF','KE_dyBF',
    'WV_dyBP','WL_dyBP','WI_dyBP','SE_dyBP','KE_dyBP',
        'WV_dyAP','WL_dyAP','WI_dyAP','SE_dyAP','KE_dyAP',
  'WV_dyAM','WL_dyAM','WI_dyAM','SE_dyAM','KE_dyAM',
     'WV_dBF','WL_dBF','WI_dBF','SE_dBF','KE_dBF',
         'WV_dED','WL_dED','WI_dED','SE_dED','KE_dED',
         'WV_dAD','WL_dAD','WI_dAD','SE_dAD','KE_dAD',
        'WV_dAF','WL_dAF','WI_dAF','SE_dAF','KE_dAF',
       'WV_dBD','WL_dBD','WI_dBD','SE_dBD','KE_dBD',
         'WV_dAR','WL_dAR','WI_dAR','SE_dAR','KE_dAR',
         'WV_dAH','WL_dAH','WI_dAH','SE_dAH','KE_dAH',
         'WV_dBH','WL_dBH','WI_dBH','SE_dBH','KE_dBH',
        'WV_dCH','WL_dCH','WI_dCH','SE_dCH','KE_dCH',
         'WV_dAS','WL_dAS','WI_dAS','SE_dAS','KE_dAS',
        'WV_dBS','WL_dBS','WI_dBS','SE_dBS','KE_dBS'

**Comment by dan800** [comment]
@cecilehannay 
**fincl5 monthly with TEM for @dan800. @fvitt: do I need to change phys_grid_ctem_nfreq=-6**
No, that's the frequency at which TEM diags are calculated as the model runs - i.e., it only needs to be done every 6 hours. The output is the average of all those calculations.
**Do you want these on the native grid or interpolate on f09 grid?**
The grid is set by:
phys_grid_ctem_za_nlat=90
So it's output on 2 degree resolution

**Comment by cecilehannay** [comment]
@PeterHjortLauritzen and @swrneale: do you want your variables on native grid or f09 grid?

**Comment by PeterHjortLauritzen** [comment]
native

**Comment by PeterHjortLauritzen** [comment]
can you add "EFIX" to the erngy fincl? thanks

**Comment by dan800** [comment]
@cecilehannay I suggest the aerosol fields be put into their own history file - they will make looking at monthly mean time series incredibly slow otherwise.

**Comment by cecilehannay** [comment]
Should 'AODVISdn' go in that list too? Or do I keep it in the h0 file. 
@tilmes: do you want native or f09 grid? 

I could create ``fincl6`` 
```
fincl6 = 'AQSO4_H2O2','AQSO4_O3', 'bc_a1', 'bc_a4', 'dst_a1', 'dst_a2', 'dst_a3', 'ncl_a1',
'ncl_a1', 'ncl_a2', 'ncl_a3', 'pom_a1', 'pom_a4', 'so4_a1', 'so4_a2', 'so4_a3',
'soa_a1', 'num_a1', 'num_a2', 'num_a3', 'num_a4',
'bc_a1SFWET', 'bc_a4SFWET', 'dst_a1SFWET', 'dst_a2SFWET', 'dst_a3SFWET', 'ncl_a1SFWET',
'ncl_a2SFWET', 'ncl_a3SFWET', 'pom_a1SFWET', 'pom_a4SFWET', 'so4_a1SFWET', 'so4_a2SFWET', 'so4_a3SFWET', 'soa_a1SFWET', 'soa_a2SFWET', 'bc_c1SFWET', 'bc_c4SFWET', 'dst_c1SFWET', 'dst_c2SFWET', 'dst_c3SFWET', 'ncl_c1SFWET', 'ncl_c2SFWET', 'ncl_c3SFWET', 'pom_c1SFWET', 'pom_c4SFWET', 'so4_c1SFWET', 'so4_c2SFWET', 'so4_c3SFWET', 'soa_c1SFWET', 'soa_c2SFWET', 'bc_a1DDF', 'bc_a4DDF', 'dst_a1DDF', 'dst_a2DDF', 'dst_a3DDF', 'ncl_a1DDF', 'ncl_a2DDF', 'ncl_a3DDF', 'pom_a1DDF', 'pom_a4DDF', 'so4_a1DDF', 'so4_a2DDF', 'so4_a3DDF', 'soa_a1DDF', 'soa_a2DDF', 'so4_a1_CLXF', 'so4_a2_CLXF', 'SFbc_a4', 'SFpom_a4', 'SFso4_a1', 'SFso4_a2',
'so4_a1_sfgaex1', 'so4_a2_sfgaex1', 'so4_a3_sfgaex1', 'soa_a1_sfgaex1', 'soa_a2_sfgaex1',
'SFdst_a1','SFdst_a2', 'SFdst_a3', 'SFncl_a1', 'SFncl_a2', 'SFncl_a3',
'num_a2_sfnnuc1'
```

**Comment by tilmes** [comment]
AODVISdn can go into the h0 files. 
Also, I can work on the namelist additions for this next, just was wanted to make sure it is reasonable.

**Comment by cecilehannay** [comment]
I am going to submit a one-month run with the following ``user_nl_cam``. If it is successful, I will extent the run. 
 
```

mfilt		    =       0,       5,     20,      40,      12,       1,      1
nhtfrq              =       0,     -24,    -24,      -3,       0,       0,      0
ndens               =       2,       2,      2,       2,       2,       1,      2
interpolate_output  =  .true.,  .true., .true., .false., .false., .false.,  .true.
interpolate_nlat    =     192,     192,    192,     192,     192,     192,   192
interpolate_nlon    =     288,     288,    288,     288,     288,     288,   288 


fexcl1 = ' '  

empty_htapes = .true.

fincl1 = 'ACTNI', 'ACTNL', 'ACTREI', 'ACTREL', 'AODDUST', 'AODVIS', 'AODVISdn','BURDENBC', 'BURDENDUST', 'BURDENPOM', 'BURDENSEASALT', 
'BURDENSO4', 'BURDENSOA', 'CAPE', 'CCN3', 'CDNUMC', 'CH4', 'CLDHGH', 'CLDICE', 'CLDLIQ', 'CLDLOW', 'CLDMED', 'CLDTOT', 'CLOUD', 'CMFMC_DP', 
'CT_H2O', 'DCQ', 'DQCORE', 'DTCOND', 'DTCORE', 'DTV', 'EVAPPREC', 'EVAPSNOW', 'FCTI', 'FCTL', 'FICE', 'FLDS', 'FLNS', 'FLNSC', 'FLNT', 'FLNTC', 'FLUT', 
'FREQZM', 'FSDS', 'FSDSC', 'FSNS', 'FSNSC', 'FSNT', 'FSNTC', 'FSNTOA', 'ICEFRAC', 'LANDFRAC', 'LHFLX', 'LWCF', 'MPDICE', 'MPDLIQ', 'MPDQ', 'MPDT', 
'OCNFRAC', 'OMEGA', 'OMEGA500', 'PBLH', 'PHIS', 'PINT', 'PMID', 'PRECC', 'PRECL', 'PRECSC', 'PRECSL', 'PRECT', 'PS', 'PSL', 'PTEQ', 'PTTEND', 'Q', 
'QFLX', 'QRL', 'QRS', 'QTGW', 'RCMTEND_CLUBB', 'RELHUM', 'RVMTEND_CLUBB', 'SHFLX', 'SOLIN', 'SST', 'STEND_CLUBB', 'SWCF', 
'T', 'TAUX', 'TAUY', 'TFIX', 'TGCLDIWP', 'TGCLDLWP', 'TMQ', 'TREFHT', 'TS', 'TTGW', 'U', 'U10', 'UBOT', 'UTGWORO', 'UTGW_TOTAL', 
'V', 'VBOT', 'VTGWORO', 'VTGW_TOTAL', 'WPRTP_CLUBB', 'WPTHLP_CLUBB', 'Z3', 'ZMDQ', 'ZMDT', 'N2O', 'CO2',
'CLD_MISR','FISCCP1_COSP','CLD_CAL','CLD_MISR','CLDTOT_CAL','CLDHGH_CAL', 'CLDMED_CAL','CLDLOW_CAL','CLMODIS', 'AODVISdn'


fincl2 = 'OMEGA', 'PMID', 'PS', 'Q', 'QRL', 'QRS', 'T', 'TROP_P', 'TROP_T', 'U', 'V', 'Z3'

fincl3 = 'PRECT', 'PRECC', 'FLUT', 'U850', 'U200', 'V850', 'V200', 'OMEGA', 'PSL'

fincl4 =  'PRECC','PRECL'

fincl5 = 'VTHzaphys','WTHzaphys','UVzaphys','UWzaphys','Uzm', 'Wzm', 'Vzm', 'THzm'

fincl6 =  'WV_phBF','WL_phBF','WI_phBF','SE_phBF','KE_phBF',
'WV_phBP','WL_phBP','WI_phBP','SE_phBP','KE_phBP',
'WV_phAP','WL_phAP','WI_phAP','SE_phAP','KE_phAP',
'WV_phAM','WL_phAM','WI_phAM','SE_phAM','KE_phAM',
'WV_dyBF','WL_dyBF','WI_dyBF','SE_dyBF','KE_dyBF',
'WV_dyBP','WL_dyBP','WI_dyBP','SE_dyBP','KE_dyBP',
'WV_dyAP','WL_dyAP','WI_dyAP','SE_dyAP','KE_dyAP',
'WV_dyAM','WL_dyAM','WI_dyAM','SE_dyAM','KE_dyAM',
'WV_dBF','WL_dBF','WI_dBF','SE_dBF','KE_dBF',
'WV_dED','WL_dED','WI_dED','SE_dED','KE_dED',
'WV_dAD','WL_dAD','WI_dAD','SE_dAD','KE_dAD',
'WV_dAF','WL_dAF','WI_dAF','SE_dAF','KE_dAF',
'WV_dBD','WL_dBD','WI_dBD','SE_dBD','KE_dBD',
'WV_dAR','WL_dAR','WI_dAR','SE_dAR','KE_dAR',
'WV_dAH','WL_dAH','WI_dAH','SE_dAH','KE_dAH',
'WV_dBH','WL_dBH','WI_dBH','SE_dBH','KE_dBH',
'WV_dCH','WL_dCH','WI_dCH','SE_dCH','KE_dCH',
'WV_dAS','WL_dAS','WI_dAS','SE_dAS','KE_dAS',
'WV_dBS','WL_dBS','WI_dBS','SE_dBS','KE_dBS',
'EFIX'


fincl7= 'AQSO4_H2O2','AQSO4_O3',
'bc_a1', 'bc_a4', 'dst_a1', 'dst_a2', 'dst_a3', 'ncl_a1',
'ncl_a1', 'ncl_a2', 'ncl_a3', 'pom_a1', 'pom_a4', 'so4_a1', 'so4_a2', 'so4_a3',
'soa_a1', 'soa_a2', 'bc_c1', 'bc_c4', 'dst_c1', 'dst_c2', 'dst_c3', 'ncl_c1',
'ncl_c1', 'ncl_c2', 'ncl_c3', 'pom_c1', 'pom_c4', 'so4_c1', 'so4_c2', 'so4_c3',
'soa_c1', 'soa_c2', 'num_a1', 'num_a2', 'num_a3', 'num_a4', 'num_c1', 'num_c2',
'num_c3', 'num_c4', 'bc_a1SFWET', 'bc_a4SFWET', 'dst_a1SFWET', 'dst_a2SFWET', 'dst_a3SFWET', 'ncl_a1SFWET',
'ncl_a2SFWET', 'ncl_a3SFWET', 'pom_a1SFWET', 'pom_a4SFWET', 'so4_a1SFWET', 'so4_a2SFWET', 'so4_a3SFWET', 'soa_a1SFWET',
'soa_a2SFWET', 'bc_c1SFWET', 'bc_c4SFWET', 'dst_c1SFWET', 'dst_c2SFWET', 'dst_c3SFWET', 'ncl_c1SFWET', 'ncl_c2SFWET',
'ncl_c3SFWET', 'pom_c1SFWET', 'pom_c4SFWET', 'so4_c1SFWET', 'so4_c2SFWET', 'so4_c3SFWET', 'soa_c1SFWET', 'soa_c2SFWET',
'bc_a1DDF', 'bc_a4DDF', 'dst_a1DDF', 'dst_a2DDF', 'dst_a3DDF', 'ncl_a1DDF', 'ncl_a2DDF', 'ncl_a3DDF',
'pom_a1DDF', 'pom_a4DDF', 'so4_a1DDF', 'so4_a2DDF', 'so4_a3DDF', 'soa_a1DDF', 'soa_a2DDF', 'bc_c1DDF',
'bc_c4DDF', 'dst_c1DDF', 'dst_c2DDF', 'dst_c3DDF', 'ncl_c1DDF', 'ncl_c2DDF', 'ncl_c3DDF', 'pom_c1DDF',
'pom_c4DDF', 'so4_c1DDF', 'so4_c2DDF', 'so4_c3DDF', 'soa_c1DDF', 'soa_c2DDF',
'num_a1DDF', 'num_a2DDF',
'num_a3DDF', 'num_a4DDF', 'num_c1DDF', 'num_c2DDF', 'num_c3DDF', 'num_c4DDF', 'bc_a4_CLXF', 'pom_a4_CLXF',
'so4_a1_CLXF', 'so4_a2_CLXF', 'num_a1_CLXF', 'num_a2_CLXF', 'SFbc_a4', 'SFpom_a4', 'SFso4_a1', 'SFso4_a2',
'SFnum_a1', 'SFnum_a2', 'SFnum_a3', 'so4_a1_sfgaex1', 'so4_a2_sfgaex1', 'so4_a3_sfgaex1', 'soa_a1_sfgaex1', 'soa_a2_sfgaex1',
'so4_a2_sfnnuc1', 'so4_c1AQH2SO4', 'so4_c2AQH2SO4', 'so4_c3AQH2SO4', 'so4_c1AQSO4', 'so4_c2AQSO4', 'so4_c3AQSO4', 'SFdst_a1',
'SFdst_a2', 'SFdst_a3', 'SFncl_a1', 'SFncl_a2', 'SFncl_a3', 'soa_a1_CHML', 'soa_a1_CHML', 'so4_a1_CHMP',
'so4_a2_CHMP', 'so4_a3_CHMP', 'soa_a1_CHMP', 'soa_a1_CHMP', 'H2SO4_sfnnuc1',
'num_a2_sfnnuc1'


phys_grid_ctem_nfreq=-6
phys_grid_ctem_zm_nbas=120
phys_grid_ctem_za_nlat=90

ncdata = '/glade/p/cesm/amwg_dev/juliob/FWsc_ne30pg3_58L_GRID_48_taperstart10km_lowtop_BL10_v3_beta1p75_Top_43km.nc'

clubb_l_predict_upwp_vpwp=.true. 
clubb_l_mono_flux_lim_um   = .true.  
clubb_l_mono_flux_lim_vm   = .true.  
clubb_c_uu_shr = 0.1
clubb_c7=0.1

dust_emis_fact         = 0.80D0


```

**Comment by dan800** [comment]
@cecilehannay  If you have not done this yet, it would be good to have all the prognostic GHGs - so include 'CFC11' and 'CFC12' in the h0s - we don't want any surprises there.

**Comment by tilmes** [comment]
you can use this list for fincl7, which is  a little shorter:
AQSO4_H2O2','AQSO4_O3', 'bc_a1', 'bc_a4', 'dst_a1', 'dst_a2', 'dst_a3', 'ncl_a1',
'ncl_a1', 'ncl_a2', 'ncl_a3', 'pom_a1', 'pom_a4', 'so4_a1', 'so4_a2', 'so4_a3',
'soa_a1', 'num_a1', 'num_a2', 'num_a3', 'num_a4',
'bc_a1SFWET', 'bc_a4SFWET', 'dst_a1SFWET', 'dst_a2SFWET', 'dst_a3SFWET', 'ncl_a1SFWET',
'ncl_a2SFWET', 'ncl_a3SFWET', 'pom_a1SFWET', 'pom_a4SFWET', 'so4_a1SFWET', 'so4_a2SFWET', 'so4_a3SFWET', 'soa_a1SFWET',
'soa_a2SFWET', 'bc_c1SFWET', 'bc_c4SFWET', 'dst_c1SFWET', 'dst_c2SFWET', 'dst_c3SFWET', 'ncl_c1SFWET', 'ncl_c2SFWET',
'ncl_c3SFWET', 'pom_c1SFWET', 'pom_c4SFWET', 'so4_c1SFWET', 'so4_c2SFWET', 'so4_c3SFWET', 'soa_c1SFWET', 'soa_c2SFWET',
'bc_a1DDF', 'bc_a4DDF', 'dst_a1DDF', 'dst_a2DDF', 'dst_a3DDF', 'ncl_a1DDF', 'ncl_a2DDF', 'ncl_a3DDF',
'pom_a1DDF', 'pom_a4DDF', 'so4_a1DDF', 'so4_a2DDF', 'so4_a3DDF', 'soa_a1DDF', 'soa_a2DDF',
'so4_a1_CLXF', 'so4_a2_CLXF', 'SFbc_a4', 'SFpom_a4', 'SFso4_a1', 'SFso4_a2',
'so4_a1_sfgaex1', 'so4_a2_sfgaex1', 'so4_a3_sfgaex1', 'soa_a1_sfgaex1', 'soa_a2_sfgaex1',
'SFdst_a1','SFdst_a2', 'SFdst_a3', 'SFncl_a1', 'SFncl_a2', 'SFncl_a3',
'num_a2_sfnnuc1'
working on the other namelist additions for the shorter list asap

**Comment by tilmes** [comment]
@cecilehannay I changed the list I had a couple of variables missing

**Comment by cecilehannay** [comment]
Run started as: 
https://github.com/NCAR/amwg_dev/issues/234
