### ISSUE TITLE
Repeat baseline with namelist change

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/amwg_dev#243]
### Description of the run

repeat baseline https://github.com/NCAR/amwg_dev/issues/240 with namelist change lcp_moist=.false. (2 year run enough)

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@PeterHjortLauritzen @adamrher 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
See: #244
