### ISSUE TITLE
Increasing LWCF without major impact on SWCF

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/amwg_dev#246]
In many respects simulations with DCS=250 microns (instead of current default of 500) look good.  However, global LWCF is reduced to value below 20 Wm-2 from a value around 23 Wm-2 in default.  Current CERES-EBAF estimates are closer to 25 Wm-2. 

This discussion is meant to collect ideas on how to target LWCF in the model without significant imapct on SWCF.

**Comment by swrneale** [comment]
Given these sensitivities I'm wondering whether we might investigate ZM parameters for LWCF increases and increased convective depth. The two that show the most sensitivity (tiedke_add and dmpdz) certainly aren't set in stone. In fact I think we should entertain reducing dmpdz to -0.8e-3 from 1.e-3. The former value is the one used in the E3SMv1 model which had 72 vertical levels, so it could be an appropriate change. We could also juice the tiedke_add to 1.5.
