### ISSUE TITLE
Repeat #235 with the new land tag

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/amwg_dev#249]
### Description of the run

I talked to @JulioTBacmeister  and he suggested to starting a new run to repeat #235 but with the new land tag. It was based on discussions he had with @cacraigucar. 

A few questions for the team: 
- which cam tag do I use for that purpose? Should I use cam6_3_105 (like #235) + modified external for the land? Or something else? 
- which land tag do we want for that run ? Do we need to add somebody from the land to this thread? 

### Source modifications

?

### Sandbox

?

### Contact info

@JulioTBacmeister, @cacraigucar

### Any other relevant information

Enter relevant info

**Comment by adamrher** [comment]
you don't need to update the externals, or tag. The current external is ctsm dev120 and supports the new clm 5.1 physics. See https://github.com/ESCOMP/CAM/issues/789 for how to modify the long name compset.

**Comment by adamrher** [comment]
I think we should use new 5.2 surface datasets though, which will require some ctsm source mods. Ill fill in that detail ~2pm here.

**Comment by adamrher** [comment]
or Ill just do it now! clm source mods and namelists:

```
/glade/u/home/oleson/run_hist_1850_files/SPINUP/casefiles_foradam/SourceMods/ctsm5.1.dev120/src.clm/*
fsurdat = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/surfdata_ne30np4.pg3_SSP5-8.5_78pfts_CMIP6_1850-2100_c230227.nc'
flanduse_timeseries = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/landuse.timeseries_ne30np4.pg3_SSP5-8.5_78_CMIP6_1850-2100_c230227.nc'
```

**Comment by JulioTBacmeister** [comment]
Basic question: Are there any issues initializing the new land model?

**Comment by JulioTBacmeister** [comment]
I see that, but what still concerns me is that the point of including the new land in our current FLTHIST tuning runs is that we want to include changes in the land that might affect radiative balances.  However, if the ICs for the new land are goofy (even if functional) don't we run the risk of being even further from the new climate than we are using the older (but spun up) land?

**Comment by adamrher** [comment]
@billsacks @wwieder are there any issues using a restart file from a CLM50 run as the inic for this CLM51 run?

**Comment by wwieder** [comment]
I wouldn't want to do a production run that way, but it seems like a good option for your purposes here.  Another option could be to run with initial conditions from an offline version of CLM51, but I don't think we even have one of those using the CTSM5.2 surface dataset you're using.  @olyson may also have suggestions?

**Comment by olyson** [comment]
Regarding CLM SourceMods for this particular run, I have a reduced set of mods here:

/glade/u/home/oleson/run_hist_1850_files/SPINUP/casefiles_cecile/SourceMods/ctsm5.1.dev120/src.clm

I reduced this from the set that Adam listed above because we really only needed some of those to do some more coupler history sanity checks.
The ones I'm pointing to do include a bug fix for the negative h2osoi_ice that Cecile encountered.  This is the basically the same as what Cecile has been using, I've just loosened the tolerance a bit more.  @billsacks is working on a more robust fix, but we can use this for now.

Regarding @wwieder 's question about CDEPS/CMEPS SourceMods, we shouldn't need any.  @adamrher confirmed that the CMEPS tag being used here has the bug fix and the CDEPS mods are only needed for the land spinup itself.

The user_nl_clm that Adam lists above is correct (the fsurdat and landuse_timeseries files).  I agree we might as well use these.

Regarding the initial conditions, it looks like the simulation that this case is going to be based on (f.cam6_3_105.FLTHIST_v0a.ne30.001?) comes out of the box with

 finidat = 'f.e21.FWscHIST_BGC.ne30_ne30_mg17_L48_revert-J.001.clm2.r.1989-01-01-00000.nc'

So I assume this simulation will start in 1989?  
I think a possible alternative to using the default finidat would be to use a restart from a CTSM5.1 historical I did some time ago.  This would include most of the CTSM5.1 physics (e.g., Birch's phenology changes and biomass heat storage) but wouldn't have the new surface dataset changes.  On the other hand the forcing is GSWP3V1.  The restart file for 1989-01-01 is here:

/glade/p/cgd/tss/people/oleson/CLM50_CTSM51_LAND_ONLY_RELEASE/ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist/rest/1989-01-01-00000/ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist.clm2.r.1989-01-01-00000.nc

Other than that I don't think we have anything more appropriate than the default.

**Comment by adamrher** [comment]
Thanks, Keith and Will. @cecilehannay to summarize the mods needed for this run:

compset:
```
HIST_CAM%DEV%LT%GHGMAM4_CLM51%SP_CICE%PRES_DOCN%DOM_MOSART_SGLC_SWAV
```

SourceMods:
```
/glade/u/home/oleson/run_hist_1850_files/SPINUP/casefiles_cecile/SourceMods/ctsm5.1.dev120/src.clm/*
```

CLM namelists
```
finidat = '/glade/p/cgd/tss/people/oleson/CLM50_CTSM51_LAND_ONLY_RELEASE/ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist/rest/1989-01-01-00000/ctsm51_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist.clm2.r.1989-01-01-00000.nc'
fsurdat = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/surfdata_ne30np4.pg3_SSP5-8.5_78pfts_CMIP6_1850-2100_c230227.nc'
flanduse_timeseries = '/glade/work/slevis/git/mksurfdata_toolchain/tools/mksurfdata_esmf/landuse.timeseries_ne30np4.pg3_SSP5-8.5_78_CMIP6_1850-2100_c230227.nc'
```

where I'm suggesting we use the CLM51 restart file from a DATM=GSWP3V1 run from Keith.

**Comment by olyson** [comment]
Oh, I didn't realize these were SP (satellite phenology) runs, sorry.  The initial file I mentioned was from a BGC-Crop simulation.  In that case, if we do decide to use an initial file from a CTSM5.1 physics run then I would use the SP version that I ran:

/glade/p/cgd/tss/people/oleson/CLM50_CTSM51_LAND_ONLY_RELEASE/ctsm51sp_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist/rest/1989-01-01-00000/ctsm51sp_cesm23a02cPPEn08ctsm51d030_1deg_GSWP3V1_hist.clm2.r.1989-01-01-00000.nc

**Comment by adamrher** [comment]
Got it. Yes, the convention has been for us to use SP in F-case evaluations, but we will use (and have been using) BGC_CROP for the coupled eval runs. (In contrast, the CPLHIST F-case run #245 will use BGC_CROP).

**Comment by olyson** [comment]
Ok thanks, just to note then that some of the CTSM5.1 physics changes (e.g., related to prognostic phenology) won't apply in these SP cases.

**Comment by cecilehannay** [comment]
One more question: do we want a long run or a short run (ie 1979 or 1995 start date?)

**Comment by cecilehannay** [comment]
I just talked to @JulioTBacmeister. We will start two runs. One with Peter's energy branch and one with the trunk. Both runs will start in 1979.

**Comment by cecilehannay** [comment]
@jtruesdal and @PeterHjortLauritzen: 
is your branch updated to cam6_3_107? I am getting ready to start two new runs with the new land one with the trunk and one with your branch. 
I was going to use cam6_3_107. But if your branch is not updated, I could revert to cam6_3_106.

**Comment by PeterHjortLauritzen** [comment]
@jtruesdal is merging ebudget_dev_update branch up to 6_3_107

**Comment by cecilehannay** [comment]
Last, last question, before I push on the submit button. 

In previous runs, we output 2 sets of daily files: ``fincl2`` and ``fincl3`` with teh variables
```
fincl2 = 'OMEGA', 'PMID', 'PS', 'Q', 'QRL', 'QRS', 'T', 'TROP_P', 'TROP_T', 'U', 'V', 'Z3'
fincl3 = 'PRECT', 'PRECC', 'FLUT', 'U850', 'U200', 'V850', 'V200', 'OMEGA', 'PSL'
```
The ``fincl2`` output is huge and it seems that nobody is using it. (I asked before and nobody said they are using this at the moment. I know @swrneale wants ``fincl3``. 

I am planning to remove fincl2 from these runs except if I hear otherwise.

**Comment by adamrher** [comment]
Fine by me. At this stage I'm just looking at monthly 3D fields.

**Comment by swrneale** [comment]
I agree too. The whole of fincl3 is the same as 20% of one of the fincl2 variables, so easy to keep. I'll try taking a look at these next week.

**Comment by wwieder** [comment]
I'm not sure where to ask this, so I'll post it here.  @adamrher or someone who's running F cases after your figure out the CAM tuning can you write out the ground lightning flux being generated by the model. We're interested in using this for fire ignitions in CESM3 if possible.

**Comment by JulioTBacmeister** [comment]
@wwieder do you know what this variable is called in CAM? @cecilehannay can add it to the upcoming F-case runs.

**Comment by wwieder** [comment]
I don't know... maybe `LGHTNG_CLD2GRND`? 

Last I checked the [PR that @fvitt was working on](https://github.com/ESCOMP/CAM/pull/747) wasn't yet on the main CAM dev branch. 

This can be low priority, as we're currently reading in a one year climatology of 2h data from NASA. As such, most helpful for us would be some kind of short duration, high frequency output.

**Comment by cacraigucar** [comment]
> I don't know... maybe `LGHTNG_CLD2GRND`?
> 
> Last I checked the [PR that @fvitt was working on](https://github.com/ESCOMP/CAM/pull/747) wasn't yet on the main CAM dev branch.
> 
> This can be low priority, as we're currently reading in a one year climatology of 2h data from NASA. As such, most helpful for us would be some kind of short duration, high frequency output.

Yes, that is correct, this PR has not been merged in yet.  It is awaiting a CMEPS PR being made.

**Comment by adamrher** [comment]
@cacraigucar that lightning PR or related issues should probably have the coupled-eval3 tag to indicate it's a requirement for CESM3.

**Comment by cacraigucar** [comment]
It is at the top of the full review column in our CAM projects page, but I'll go ahead and add that tag

**Comment by cecilehannay** [comment]
See: #250
