### ISSUE TITLE
Adding "Ben and Julio Favorite tuning" 

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/amwg_dev#254]
### Description of the run

At the CAM7 meeting, we decided to start a new run with: 
https://github.com/NCAR/amwg_dev/issues/252 + "Ben and Julio Favoroite tuning" 

We were waiting to see to get the ADF for the first few years of #252 to make that there was no showstoppers.  

@justin-richling is running the ADF but I would like to get the favorite tuning parameters from @bstephens82 and @JulioTBacmeister. 

### Contact info
@bstephens82 and @JulioTBacmeister.

**Comment by JulioTBacmeister** [comment]
Case directory for Ben's run with "best" parameters:
/glade/u/home/stepheba/cam99/cime/scripts/dflt099_vtrmf0.5_lwpexp2.4_dcs400/

Diags:
https://webext.cgd.ucar.edu/F2000climo/dflt099_vtrmf0.5_lwpexp2.4_dcs400/atm/dflt099_vtrmf0.5_lwpexp2.4_dcs400-obs.0001_1/

**Comment by cecilehannay** [comment]
The tuning parameters are:
```
micro_mg_dcs=0.0004
micro_mg_autocon_lwp_exp=2.4
micro_mg_vtrmi_factor=0.5
```

**Comment by cecilehannay** [comment]
Run started: https://github.com/NCAR/amwg_dev/issues/255
