### ISSUE TITLE
add lightning output frequency to runs for land folks

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#256]
### Description of the run

@wwieder requests the lightning "flux" sent to the land model be output. It's not clear if this just requires adding a history field. We had previously suggested the variable ``` LGHTNG_CLD2GRND ``` but not clear if that variable populates with the lightning flux sent to CTSM since https://github.com/ESCOMP/CAM/pull/747 (which is the PR that added functionality to send lightning to the land model).

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

Contact information

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
Are we ready to start this run?

**Comment by adamrher** [comment]
its not really a run request. its just a way for me to document that the land folks want this variable. I'd wait until they chime in. Adding @olyson.

**Comment by olyson** [comment]
Thanks for posting this @adamrher .  I've been looking at this a bit and see a couple of CAM history variables of interest: FLASHFRQ (flash frequency in grid box per minute) and LGHTNG_CLD2GRND (cloud-to-ground lightning flash rate).  I assume that it is the equivalent of LGHTNG_CLD2GRND that CAM now exports through the namelist variable atm_provides_lightning but it would be good to get confirmation of this.
As a first step we'd like to compare these with the 2-hourly climatology for 1995-2013 from NASA that we currently use in CTSM.  The NASA product is a total flashes quantity.  We then multiply this by a factor that is a function of latitude in the code to get cloud to ground flashes.  
So it would be nice to get both FLASHFRQ  and LGHTNG_CLD2GRND  at 2-hourly resolution in a CAM run so we could compare both total flashes and cloud to ground.
Perhaps we could get this output from a portion of the coupler history F-case you are planning to do for say 10 years?  If this is too much to ask, we can probably do our own run.
Obviously, let me know if I have these CAM variables wrong.

Our next step would be to take the data from CAM and create a new climatology file and then force CTSM with it in a land-only simulation.

**Comment by adamrher** [comment]
Re: the outfld variable ```LGHTNG_CLD2GRND```

> I assume that it is the equivalent of LGHTNG_CLD2GRND that CAM now exports through the namelist variable atm_provides_lightning but it would be good to get confirmation of this.

@fvitt do you happen to know if this is true?

**Comment by olyson** [comment]
As a first step, we could also just output monthly averages of those variables for 10 years.

**Comment by fvitt** [comment]
> Re: the outfld variable `LGHTNG_CLD2GRND`
> 
> > I assume that it is the equivalent of LGHTNG_CLD2GRND that CAM now exports through the namelist variable atm_provides_lightning but it would be good to get confirmation of this.
> 
> @fvitt do you happen to know if this is true?

That's correct.

**Comment by adamrher** [comment]
Thanks Francis.

Keith, I don't think there would be any issue in having two-hourly output of ```LGHTNG_CLD2GRND``` for one of our upcoming simulations. Instantaneous or averaged? you want it interpolated to the f09 grid or on the native se grid? Are you suggesting the CPLHIST run because it is running BGC-CROP? If you're OK with SP, I'd rather graft this onto a run that's not 100 years long ... but I guess If we flipped it on for the final 10 years that'd be fine --- do you know if you can change history fields mid-run or do you have to recompile?

**Comment by olyson** [comment]
Interpolated to the f09 grid would be great.  I was suggesting CPLHIST because we only use lightning in BGC-Crop mode but I think data generated from one of your SP simulations would be fine for now.
I think averaged but I'll have to check and see what the metadata for the NASA data says.

**Comment by olyson** [comment]
It looks like averaged would be appropriate.

**Comment by cecilehannay** [comment]
I don't see this variable LGHTNG_CLD2GRND in the master field list. Am i missing something?

**Comment by olyson** [comment]
@cecilehannay , I see it in src/chemistry/mozart/mo_lightning.F90:

call addfld( 'LGHTNG_CLD2GRND', horiz_only,  'I', 'min-1', 'clound-to-ground lightning flash rate') ! clound to ground flash frequency
call outfld( 'LGHTNG_CLD2GRND', cld2grnd_flash_freq, pcols, lchnk )

I was able to output it in a short run with cam6_3_109.
I'm not familiar with CAM's master field list however.

**Comment by adamrher** [comment]
The only thing I see that can cause that addfld call not to execute is this statement a few blocks up in ```lightning_init```

```
    calc_lightning = cldtop_ndx>0 .and. cldbot_ndx>0

    if (.not.calc_lightning) return
```

Those cldtop_ indices should be equal to 1 (?), as they are added to the pbuf in convect_diagnostics_register. But a value of 1 wouldn't trigger that if statement. Maybe this isn't it. But I don't get this since ```lightning_init``` is being called in all runs, and so that addfld should take.

**Comment by JulioTBacmeister** [comment]
OK.  So it seems this should run with 'LGHTNG_CLD2GRND'. I don't understand then how the master field list is accumulated.

**Comment by cecilehannay** [comment]
I would include 2-hour output of 'LGHTNG_CLD2GRND' in: https://github.com/NCAR/amwg_dev/issues/259

**Comment by adamrher** [comment]
I don't think we should close this request until we figure out why we can't output ```LGHTNG_CLD2GRND```

**Comment by adamrher** [comment]
Ah, @cecilehannay were you looking at the master field list from a run using a tag older than cam6_3_108? Because this history variable was added in the cam6_3_108, and is not available on earlier tags.

**Comment by cecilehannay** [comment]
Yes, I was looking at the master field list in the latest run I did which was with cam6_3_107On May 5, 2023, at 4:53 PM, Adam Herrington ***@***.***> wrote:﻿
Ah, @cecilehannay were you looking at the master field list from a run using a tag older than cam6_3_108? Because this history variable was added in the cam6_3_108, and is not available on earlier tags.

**Comment by adamrher** [comment]
Got it. So there are no issues and this can remain closed. Have a good weekend!
