### ISSUE TITLE
start a FMTHIST

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/amwg_dev#257]
### Description of the run

We want to test the new compset FMTHIST.

@JulioTBacmeister has some suggestions for gw tunning in this run. 

### Suffix in the casename

N/A

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

LAtest tag

### Contact info

Contact information

### Any other relevant information

Enter relevant info for this run: @tilmes, @JulioTBacmeister, @adamrher, @dan800

**Comment by dan800** [comment]
@JulioTBacmeister So non-oro GWs ON, tau_0_ubc = True, zero flux condition on all constituents (including water this time). GW settings out of the box to be the same as SE WACCM. Is that a good start?

**Comment by cecilehannay** [comment]
Started as: https://github.com/NCAR/amwg_dev/issues/260
