### ISSUE TITLE
Trying to get more OGW drag in the stratosphere

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/amwg_dev#264]
### Description of the run

Run tries to change partition between low level drag and propagating waves in the direction of more propagating OGW waves

Like #259 except with:

 effgw_rdg_beta		= 2.0D0
 effgw_rdg_beta_max	= 2.0D0

 rdg_beta_cd_llb		= 0.25D0

### Suffix in the casename

Suffix

### Namelist modifications

effgw_rdg_beta		= 2.0D0
 effgw_rdg_beta_max	= 2.0D0

 rdg_beta_cd_llb		= 0.25D0

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

Contact information

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
Run started as: https://github.com/NCAR/amwg_dev/issues/268
