### ISSUE TITLE
Repeat non-OGW run with latest tag

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/amwg_dev#265]
### Description of the run

Want to see what effect non-orographic GW have in latest tag.  This should repeat #240 except with 109 or 110

### Suffix in the casename

Suffix

### Namelist modifications

use_gw_convect_dp   = .true.  
use_gw_front        = .true.
tau_0_ubc = .true.

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@JulioTBacmeister @dan800 @tilmes

### Any other relevant information

Enter relevant info

**Comment by dan800** [comment]
And tau_0_ubc = .true.?

**Comment by JulioTBacmeister** [comment]
Yes. Let's set tau_0_ubc=.true. in this run. I'm going to request another run like this one except with tau_0_ubc=.false.

**Comment by cecilehannay** [comment]
Run started as: https://github.com/NCAR/amwg_dev/issues/269
