### ISSUE TITLE
One line description for your simulation request

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/amwg_dev#266]
### Description of the run

To stabilize the spectral-element dynamical core with a top above ~80km we turn on the HB (Holtslag and Boville) boundary layer scheme where CLUBB is not active. This run is to assess if there are mean climate effects in the low top model.

Run setup: Like https://github.com/NCAR/amwg_dev/issues/259 (for which we have 10 year control) except for source modifications as listed below.

Run length: 10 years

### Suffix in the casename

Suffix

### Namelist modifications

user_nl_cam: add OMEGA500 to monthly mean output (if not already there)

### Source modifications

/glade/u/home/pel/src/for-hb-nohack-cam6_3_110/vertical_diffusion.F90
/glade/u/home/pel/src/for-hb-nohack-cam6_3_110/clubb_intr.F90

### Sandbox

Requested sandbox or tag

### Contact info

@PeterHjortLauritzen  @JulioTBacmeister  @adamrher  

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
Run started as: https://github.com/NCAR/amwg_dev/issues/270
