### ISSUE TITLE
non-OGW L58 w/ tau_0_ubc=.false.

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/amwg_dev#267]
### Description of the run

Exact repeat of #265 except tau_0_ubc=.false. 

### Suffix in the casename

Suffix

### Namelist modifications

tau_0_ubc=.false. 

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
Run started as: https://github.com/NCAR/amwg_dev/issues/271
