### ISSUE TITLE
Repeat FLTHIST with L32 

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/amwg_dev#274]
### Description of the run

Repeat #259 with L32 

@JulioTBacmeister 

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

Contact information

### Any other relevant information

Enter relevant info

**Comment by swrneale** [comment]
We could also flip the ZM parcel changes back to see if that has impact. It's just a switch.

**Comment by cecilehannay** [comment]
Started as #280
