### ISSUE TITLE
FLTHIST run with no external prescribed water vapor source in the stratosphere

### ISSUE THREAD

**Issue by dan800** [NCAR/amwg_dev#276]
### Description of the run

Same as #269 with the following source of water vapor removed

ext_frc_specifier		= 'H2O -> /glade/p/cesmdata/cseg/inputdata/atm/cam/chem/emis/elev/H2OemissionCH4oxidationx2_3D_L70_1849-2015_CMIP6ensAvg_c180927.nc',

This source is now calculated in line by the chemistry.

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

Contact information

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
See: https://github.com/NCAR/amwg_dev/issues/279
