### ISSUE TITLE
QBO period tuning run in FLTHIST

### ISSUE THREAD

**Issue by dan800** [NCAR/amwg_dev#278]
### Description of the run

As #276 with effgw_beres_dp = 0.30D0

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

Contact information

### Any other relevant information

Enter relevant info

**Comment by JulioTBacmeister** [comment]
Is there a change to effgw_beres here?

**Comment by cecilehannay** [comment]
Yes, the default is:
``effgw_beres_dp          = 0.55D0``

SO this run:
`effgw_beres_dp  = 0.55D0 -> 0.30D0`

**Comment by cecilehannay** [comment]
Started as #282
