### ISSUE TITLE
Tuning QBO in FLTHIST

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/amwg_dev#285]
### Description of the run

As #282 except 
 gw_qbo_hdepth_scaling = 0.25D0 -> 1.0D0

Goal:
Increase phase speeds of non-oro GW to get stronger but hopefully not faster QBO

### Suffix in the casename

Suffix

### Namelist modifications

gw_qbo_hdepth_scaling = 1.0D0 (instead of 0.25)

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@Juli

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
Run started as: https://github.com/NCAR/amwg_dev/issues/289
