### ISSUE TITLE
Decrease ZM_TAU to change tropical Pacific precip

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/amwg_dev#286]
### Description of the run

As #282 except:
zmconv_tau		=  3600.0 -> 1800.0

Goal:
Increase ZM activity to reduce SPCZ and 'red-spot' biases in W Pacific warm pool
@adamrher @swrneale : Thoughts?

### Suffix in the casename

Suffix

### Namelist modifications

zmconv_tau	= 1800.0

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@JulioTBacmeister 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
Running as: https://github.com/NCAR/amwg_dev/issues/290
