### ISSUE TITLE
Increase taubgnd to try to reduce cold biases in SH stratosphere (FMT)

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/amwg_dev#299]
### Description of the run

As #288 except
taubgnd		= 2.5D-3 instead of 1.25D-3

### Suffix in the casename

Suffix

### Namelist modifications

taubgnd		= 2.5D-3

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info
@JulioTBacmeister @tilmes @dan800

### Any other relevant information

Enter relevant info

**Comment by tilmes** [comment]
@JulioTBacmeister @cecilehannay I agree to run this as a test!

**Comment by cecilehannay** [comment]
Run completed as #312
