### ISSUE TITLE
Increase vrtmi from 1.0->1.5

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#311]
**Description:**

Same as #296 but with micro_mg_vtrmi_factor increased 1.0->1.5. The purpose is to try to reduce moisture in the tape recorder. The hope is that the large wsubi in this run (2.5) will still give us a reasonable LWCF.

**Case directory:**
Locally (if still available):
/glade/p/cesmdata/cseg/runs/cesm2_0/$CASE

On github:
https://github.com/NCAR/amwg_dev/tree/$CASE

**Sandbox:**
Locally (if still available):
/glade/work/hannay/cesm_tags/cam6_3_112

On github:
(https://github.com/ESCOMP/CAM/tree/cam6_3_112)

**Diagnostics:**
ADF diags (if available)
[https://webext.cgd.ucar.edu/FLTHIST/$CASE/atm/](https://webext.cgd.ucar.edu/FLTHIST/$CASE/atm/)

**Contacts:**

@JulioTBacmeister @PeterHjortLauritzen

**Comment by adamrher** [comment]
@JulioTBacmeister if you feel we should kick this harder to vrtmi=2.0, I'd be fine with that.

**Comment by cecilehannay** [comment]
See run #313
