### ISSUE TITLE
run with vtrmi set to 1.5

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#314]
**Description:**

We pushed vtrmi maybe a bit too hard in #313, as the LWCF went down to ~20 W/m2 (but it did recover a good tape recorder). Nonetheless we want to see if a smaller increase from 1->1.5 gives us a better cloud field.

**Case directory:**
Locally (if still available):
/glade/p/cesmdata/cseg/runs/cesm2_0/$CASE

On github:
https://github.com/NCAR/amwg_dev/tree/$CASE

**Sandbox:**
Locally (if still available):
/glade/work/hannay/cesm_tags/cam6_3_112

On github:
(https://github.com/ESCOMP/CAM/tree/cam6_3_112)

**Diagnostics:**
ADF diags (if available)
[https://webext.cgd.ucar.edu/FLTHIST/$CASE/atm/](https://webext.cgd.ucar.edu/FLTHIST/$CASE/atm/)

**Contacts:**

@PeterHjortLauritzen @JulioTBacmeister @adamrher

**Comment by cecilehannay** [comment]
Run started as #316
