### ISSUE TITLE
Science validate new HB code

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/amwg_dev#315]
### Description of the run

A new implementation of "HB when CLUBB is not active" where HB is only doing free atmosphere mixing (Richardson number based) and not PBL mixing - thanks to @tto061 (Thomas Toniazzo) for draft code https://github.com/NCAR/amwg_dev/discussions/284#discussioncomment-6307477.

See science discussion here: https://github.com/NCAR/amwg_dev/discussions/284#discussioncomment-6307477

Proposed run: Same configuration as https://github.com/NCAR/amwg_dev/issues/314 but with new HB source mods:

/glade/u/home/pel/src/for-hb-nohack-freeatm_hb-cam6_3_110/clubb_intr.F90
/glade/u/home/pel/src/for-hb-nohack-freeatm_hb-cam6_3_110/vertical_diffusion.F90
/glade/u/home/pel/src/for-hb-nohack-freeatm_hb-cam6_3_110/hb_diff.F90

### Namelist modifications

see https://github.com/NCAR/amwg_dev/issues/313

### Source modifications

/glade/u/home/pel/src/for-hb-nohack-freeatm_hb-cam6_3_110/clubb_intr.F90
/glade/u/home/pel/src/for-hb-nohack-freeatm_hb-cam6_3_110/vertical_diffusion.F90

### Sandbox

Same as https://github.com/NCAR/amwg_dev/issues/314 i.e.

### Contact info

@PeterHjortLauritzen @adamrher @JulioTBacmeister 

### Any other relevant information

Enter relevant info

**Comment by PeterHjortLauritzen** [comment]
After consultation with @cecilehannay and @adamrher baseline changed to #314 (text above edited)

**Comment by cecilehannay** [comment]
see #317
