### ISSUE TITLE
Repeat #313 with bigger wsubi

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/amwg_dev#318]
### Description of the run

Exactly as #313 except 
wsubi -> 5.0

This run tries to increase LWCF back to acceptable levels

### Suffix in the casename

Suffix

### Namelist modifications

microp_aero_wsubi_scale = 5.0 (from 2.5)

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@JulioTBacmeister @adamrher @PeterHjortLauritzen @c

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
see: #319
