### ISSUE TITLE
Test impacts of aerosol activation in liquid low clouds

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/amwg_dev#329]
### Description of the run

This run should be based on #324

The point of this experiment is to test the sensitivity of low clouds to the parameters:
 microp_aero_wsub_min	   
 microp_aero_wsub_scale

In this run these parameters should be changed from their values in #324 as follows:
 microp_aero_wsub_min		=   0.2D0    == > 0.002D0
 microp_aero_wsub_scale		=   1.D0    ==> 0.01D0

These are extreme changes. This run is meant to explore whether an effect is present. Can be short.

### Suffix in the casename

Suffix

### Namelist modifications

microp_aero_wsub_min		=   0.2D0    == > 0.002D0
microp_aero_wsub_scale		=   1.D0    ==> 0.01D0

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@JulioTBacmeister @tilmes @adamrher 

### Any other relevant information

Enter relevant info

**Comment by adamrher** [comment]
Why don't we just change ```microp_aero_wsub_scale``` and not ```microp_aero_wsub_min```? There is a similar namelist for wsubi called ```microp_aero_wsubi_min``` which we didn't need to touch to see large differences.

**Comment by cecilehannay** [comment]
See: #330
