### ISSUE TITLE
further testing wsub for liquid clouds

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/amwg_dev#331]
### Description of the run

Same as #330 except 

microp_aero_wsub_scale = 0.01D0 ==> 1.0D0

This should increase wsub where significant TKE is present.

### Suffix in the casename

Suffix

### Namelist modifications

microp_aero_wsub_scale = 0.01D0 ==> 1.0D0

### Source modifications

/glade/u/home/pel/src/for-hb-nohack-freeatm_hb-cam6_3_110/clubb_intr.F90
/glade/u/home/pel/src/for-hb-nohack-freeatm_hb-cam6_3_110/vertical_diffusion.F90
/glade/u/home/pel/src/for-hb-nohack-freeatm_hb-cam6_3_110/hb_diff.F90

### Sandbox

f.cam6_3_117

### Contact info

@JulioTBacmeister @tilmes @adamrher

### Any other relevant information

Enter relevant info

**Comment by tilmes** [comment]
@JulioTBacmeister Isn't microp_aero_wsub_scale =  1.0D0 the default we had before?
