### ISSUE TITLE
reduce cloud ice fall velocity only

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#332]
### Description of the run

vtrmi_factor reduces the fall velocity of ice, small ice and snow at the same time. Same as #324, but just lower ice fall speed by a factor 0.5 (using SourceMods).

### Suffix in the casename

slowice

### Namelist modifications

Namelist

### Source modifications

/glade/u/home/aherring/src/cam6_3_115/usr_src/slow_cld/micro_pumas_v1.F90

### Sandbox

Requested sandbox or tag

### Contact info

@adamrher @JulioTBacmeister @PeterHjortLauritzen @cbardeen 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
See: #336
