### ISSUE TITLE
Increase throughput with "science optimizations" in FLT

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/amwg_dev#339]
### Description of the run

Description:

The purpose of this run is to test various optimizations to the dynamical core for increased throughput (see details below). Only tested in 1 month long run so we will see if it is stable for a multi-year run ...

Same as https://github.com/NCAR/amwg_dev/issues/328 but using tag cam6_3_119, add NUMLIQ, NUMICE, H2O and more source mods:

/glade/u/home/pel/src/for-science-opt/dimensions_mod.F90  
/glade/u/home/pel/src/for-science-opt/global_norms_mod.F90  
/glade/u/home/pel/src/for-science-opt/prim_advance_mod.F90  
/glade/u/home/pel/src/for-science-opt/prim_advection_mod.F90  
/glade/u/home/pel/src/for-science-opt/prim_driver_mod.F90  
/glade/u/home/pel/src/for-science-opt/viscosity_mod.F90

and namelist additions:

```
se_nsplit = 1
se_rsplit = 6
se_sponge_del4_nu_div_fac  = 1
se_hypervis_subcycle = 1

se_nu_div = 1.0E15
se_nu     = 1.0E15
se_hypervis_subcycle_sponge = 2
se_nu_top = 5E5
```

### Suffix in the casename

FLTHIST_ne30.r250.opt.001

### Namelist modifications

se_nsplit = 1
se_rsplit = 6
se_sponge_del4_nu_div_fac  = 1
se_hypervis_subcycle = 1

se_nu_div = 1.0E15
se_nu     = 1.0E15
se_hypervis_subcycle_sponge = 2
se_nu_top = 5E5

### Source modifications

/glade/u/home/pel/src/for-science-opt/dimensions_mod.F90  
/glade/u/home/pel/src/for-science-opt/global_norms_mod.F90  
/glade/u/home/pel/src/for-science-opt/prim_advance_mod.F90  
/glade/u/home/pel/src/for-science-opt/prim_advection_mod.F90  
/glade/u/home/pel/src/for-science-opt/prim_driver_mod.F90  
/glade/u/home/pel/src/for-science-opt/viscosity_mod.F90

in addition to the HB mods:

/glade/u/home/pel/src/for-hb-nohack-freeatm_hb-cam6_3_110/clubb_intr.F90
/glade/u/home/pel/src/for-hb-nohack-freeatm_hb-cam6_3_110/vertical_diffusion.F90
/glade/u/home/pel/src/for-hb-nohack-freeatm_hb-cam6_3_110/hb_diff.F90

### Sandbox

 cam6_3_117

### Contact info

@cecilehannay @PeterHjortLauritzen @adamrher @JulioTBacmeister 

### Any other relevant information

Changes to dynamical core:

- reduce se_nsplit=1 (to not get noise in PS and OMEGA fields "dripple" tendencies inside rsplit-loop)
- CSLAM now runs with 2x longer time-step compared to baseline (due to se_nsplit=1 instead of 2)
- reduce divergence damping and increase velocity damping so that all modes are damped equally (se_nu=se_nu_div=se_nu_p=1E15); no increased del4 damping in sponge => se_hypevis_subcycle reduced to 1 from 4.
- slightly increase se_nu_top to 5E5 from 1.25E5 for stability
- keep condensates fixed on GLL grid (i.e. no double-advecting of condensates when using CSLAM)

More details here https://github.com/PeterHjortLauritzen/CAM/wiki/Performance-FLT

Timings for the dynamical core (left bar) and break-down of various parts of the dynamical core (advancing primitive equations, CSLAM, GLL tracer advection, vertical remapping, respectively):

<img width="1390" alt="Screen Shot 2023-07-21 at 12 10 43 PM" src="https://github.com/NCAR/amwg_dev/assets/8782989/12f08c6f-ff49-4fd1-b32b-802ade4250a7">

**Comment by cecilehannay** [comment]
Run started as #345
