### ISSUE TITLE
New baseline for FMT

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/amwg_dev#341]
### Description of the run

10 years

New tag: f.cam6_3_119

### Suffix in the casename

Suffix

### Namelist modifications

clubb_gamma_coef = 0.3
clubb_gamma_coefb = 0.3

micro_mg_dcs = 500.D-6
micro_mg_vtrmi_factor = 1.0
microp_aero_wsubi_scale  = 1.0

use_gw_convect_dp = .true.
use_gw_front =.true.
tau_0_ubc = .true.

effgw_beres_dp = 0.7 

effgw_rdg_beta = 0.5D0
effgw_rdg_beta_max = 0.5D0

### Source modifications

/glade/u/home/pel/src/for-hb-nohack-freeatm_hb-cam6_3_110/clubb_intr.F90
/glade/u/home/pel/src/for-hb-nohack-freeatm_hb-cam6_3_110/vertical_diffusion.F90
/glade/u/home/pel/src/for-hb-nohack-freeatm_hb-cam6_3_110/hb_diff.F90

### Sandbox

Requested sandbox or tag

### Contact info

@JulioTBacmeister @cecilehannay @adamrher @PeterHjortLauritzen 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
started as #347
