### ISSUE TITLE
New baseline + wsub change

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/amwg_dev#343]
### Description of the run

Same as https://github.com/NCAR/amwg_dev/issues/328 but using tag cam6_3_119 and microp_aero_wsub_scale=0.5

Add NUMLIQ, NUMICE, H2O

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

/glade/u/home/pel/src/for-hb-nohack-freeatm_hb-cam6_3_110/clubb_intr.F90
/glade/u/home/pel/src/for-hb-nohack-freeatm_hb-cam6_3_110/vertical_diffusion.F90
/glade/u/home/pel/src/for-hb-nohack-freeatm_hb-cam6_3_110/hb_diff.F90

### Sandbox

Requested sandbox or tag

### Contact info

@cecilehannay @adamrher @JulioTBacmeister @PeterHjortLauritzen 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
started as #346
