### ISSUE TITLE
FLTHIST version of new coupled baseline

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/amwg_dev#350]
### Description of the run

FLTHIST version of https://github.com/NCAR/amwg_dev/issues/349

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@cecilehannay @JulioTBacmeister  @adamrher @PeterHjortLauritzen 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
This is run #353
