### ISSUE TITLE
coupled run 1 w/ wscale_factor

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#358]
### Description of the run

Same as #356 except

```
microp_aero_wsub_scale  = 1.0->0.75
```

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@adamrher @PeterHjortLauritzen

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
@klindsay28: Gustavo mentioned to me the ocean group wanted to modify the diag_table in the next run. I don't have the new diag_table. Is it ok to start the run with the current one?

**Comment by klindsay28** [comment]
@cecilehannay , sorry I missed this earlier.
I'm not sure what Gustavo had in mind.
However, he did update some stuff in
`/glade/scratch/gmarques/for_cecile/diag_table`.
For now, please use that, replacing the case name there with your new case name.

**Comment by cecilehannay** [comment]
[klindsay28](https://github.com/klindsay28): I started the run with the diag_table I had. But I could edit the diag_table when continuing the run.

**Comment by cecilehannay** [comment]
see run #361

**Comment by klindsay28** [comment]
The changes that I'm aware of Gustavo putting into that file modified the filenames of transports across various sections.

A drawback with the current diag_table is that it is not compatible with MOM6 archive pattern matching in this tag, so the files are not getting moved to $DOUT_S/ocn/hist.

So a benefit of changing diag_table is that newly written transports files would get archived.
However, it would also change filename patterns mid-run, making analysis rather inconvenient.

Option 1: Leave diag_table as is, manually move transports files to $DOUT_S/ocn/hist

Option 2: Update diag_table, manually move existing transports files to $DOUT_S/ocn/hist, and rename them to match new filename patterns.

Option 1 seems like the least work to me. I suggest going with that.
