### ISSUE TITLE
coupled run 2 w/ wscale_factor

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#359]
### Description of the run

Same as #356 but

```
microp_aero_wsub_scale  = 1.0->0.5
clubb_gamma_coef = 0.3
clubb_gamma_coefb = 0.3
```

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@adamrher @PeterHjortLauritzen 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
see: #362
