### ISSUE TITLE
New FMT run with coupled tag

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/amwg_dev#360]
### Description of the run

To guide WACCM development I propose a new baseline with FMT using our latest coupled configuration. Details will be decided next week when @cecilehannay and @JulioTBacmeister are back. In particular, the QBO with the latest tag / configuration needs to be assessed. (the previous run used a different HB code https://github.com/NCAR/amwg_dev/issues/312)

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@PeterHjortLauritzen @cecilehannay @JulioTBacmeister @islasimpson 

### Any other relevant information

Enter relevant info

**Comment by tilmes** [comment]
@PeterHjortLauritzen I am suggesting to also do a new FMT HIST run with the recent tuning to explore improvements in the tape recorder and GW, but use the new setting that are in the latest coupled run for the LT model. So, basically this run https://github.com/NCAR/amwg_dev/issues/347 with new tag and settings.

**Comment by cecilehannay** [comment]
@adamrher and @PeterHjortLauritzen: we decided to match "34" for that run (#361) as of yesterday it was our favorite run. Based on today's results, do we want to move to another run (maybe "37" ? i.e. #367 )

**Comment by cecilehannay** [comment]
Or "33" as we have a FLTHIST for that one and we are planning to do a F1850. So many options...

**Comment by cecilehannay** [comment]
Following up the CAM7 discussion today, we decided that we will base this run on #353. This is the FLHIST equivalent of the coupled run "33"

The run directory is at: 
/glade/p/cesmdata/cseg/runs/cesm2_0/f.cam6_3_119.FMTHIST_ne30.r328_gamma0.33_soae.001


- @JulioTBacmeister could you look at the gravity wave setting to make sure this is what we want.
- @PeterHjortLauritzen could you look at the rsplit, nsplit, nu_top,...
 
 The difference between 
- the FLHIST (<) 
- and the FMTHIST (>) are:
```
<  ncdata               = 'f.cam6_3_107.FLTHIST_v0a.ne30.clm5_1.001.cam.i.1994-01-01-00000.nc'
---
>  ncdata               = '/glade/p/cesmdata/inputdata/atm/cam/inic/se/cam7_FMT_ne30pg3_mg17_L93_c221118.nc'
```
```
<  se_hypervis_subcycle         =  4 
---
>  se_hypervis_subcycle         =  3 

<  se_nsplit            =                    2 
---
>  se_nsplit            =   3  

<  se_nu_top            =  1.25e5 
---
>  se_nu_top            =  1.0e6 

<  se_rsplit            =  3 
---
>  se_rsplit            =  6 
```
```
<  effgw_beres_dp               = 0.30D0
---
>  effgw_beres_dp               = 0.70D0

<  gw_qbo_hdepth_scaling                = 1.0D0
---
>  gw_qbo_hdepth_scaling                = 0.25D0
>  gw_top_taper         = .false.
```

```
>  qbo_use_forcing              = .false.

<  ubc_file_input_type          = 'SERIAL'
<  ubc_file_path                = '/glade/p/cesmdata/inputdata/atm/cam/chem/ubc/f.e21.FWHISTBgcCrop.f09_f09_mg17.CMIP6-AMIP-WACCM.ensAvg123.cam.h0zm.UBC.195001-201412_c220322.nc'

<  ubc_specifier                = 'Q:H2O->UBC_FILE'
```

**Comment by cecilehannay** [comment]
I am also adding the variables requested by @tilmes in: https://github.com/NCAR/amwg_dev/discussions/363#discussioncomment-6763593

**Comment by cecilehannay** [comment]
@JulioTBacmeister: incase this is useful, I am adding the list of gw parameters. 

```
&gw_drag_nl
 effgw_beres_dp		= 0.70D0
 effgw_cm		= 1.D0
 effgw_rdg_beta		= 0.5D0
 effgw_rdg_beta_max		= 0.5D0
 fcrit2		= 1.0
 frontgfc		= 3.00D-15
 gw_apply_tndmax		= .false.
 gw_dc		= 2.5D0
 gw_dc_long		= 0.D0
 gw_drag_file		= '/glade/p/cesmdata/inputdata/atm/waccm/gw/newmfspectra40_dc25.nc'
 gw_limit_tau_without_eff		= .false.
 gw_lndscl_sgh		= .true. 
 gw_oro_south_fac		= 1.d0   
 gw_polar_taper		= .false.
 gw_prndl		= 0.5D0
 gw_qbo_hdepth_scaling		= 0.25D0
 gw_top_taper		= .false.
 n_rdg_beta		= 10
 pgwv		= 32
 pgwv_long		= 0
 rdg_beta_cd_llb		= 1.0D0
 tau_0_ubc		= .true.
 taubgnd		= 1.25D-3
 trpd_leewv_rdg_beta		= .false.
 use_gw_rdg_beta		= .true.
 use_gw_rdg_gamma		= .false.
/
&gw_rdg_nl
 gw_rdg_c_betamax_ds		=  0.0d0  
 gw_rdg_c_betamax_sm		=  2.0d0  
 gw_rdg_c_gammamax		=  2.0d0  
 gw_rdg_do_adjust_tauoro		= .true.  
 gw_rdg_do_backward_compat		= .false.
 gw_rdg_do_divstream		= .true.
 gw_rdg_do_smooth_regimes		= .false. 
 gw_rdg_fr_c		= 1.0D0
 gw_rdg_frx0		=  2.0d0  
 gw_rdg_frx1		=  3.0d0  
 gw_rdg_orohmin		=  0.01d0 
 gw_rdg_orom2min		=  0.1d0  
 gw_rdg_orostratmin		=  0.002d0
 gw_rdg_orovmin		=  1.0d-3 
/
 ```

**Comment by PeterHjortLauritzen** [comment]
Dycore variables look correct!

**Comment by cecilehannay** [comment]
See: #374
