### ISSUE TITLE
new b-case w/ wsub_scale and wscale_floor reduced

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#364]
**Description:**

same as #362 except the hard coded floor value of wsub is also scaled by 0.5 (10->5 cm/s). The SourceMods for the new floor value: /glade/u/home/aherring/src/cam6_3_115/usr_src/wsubfloor/ndrop.F90

**Case directory:**
Locally (if still available):
/glade/p/cesmdata/cseg/runs/cesm2_0/$CASE

On github:
https://github.com/NCAR/amwg_dev/tree/$CASE

**Sandbox:**
Locally (if still available):
 /glade/work/hannay/cesm_tags/cesm2_3_alpha13b
 
On github:
```
git clone https://github.com/ESCOMP/cesm cesm2_3_alpha13b
cd cesm2_3_alpha13b
git checkout  cesm2_3_alpha13b
./manage_externals/checkout_externals -o
```
**Diagnostics:**
AMWG diags (if available)
[https://webext.cgd.ucar.edu/BLT1850/$CASE/atm/](https://webext.cgd.ucar.edu/BLT1850/$CASE/atm/)

**Contacts:**

@JulioTBacmeister @PeterHjortLauritzen @adamrher

**Comment by cecilehannay** [comment]
See run #366
