### ISSUE TITLE
new b-case w/ wscale_factor = 0.25

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#365]
**Description:**

Same as #362 except 

```
microp_aero_wsub_scale = 0.5->0.25
```

I'd also like to relax the floor value to 0.25 as well. Those SourceMods are here:

/glade/u/home/aherring/src/cam6_3_115/usr_src/wsubfloor25/ndrop.F90

**Case directory:**
Locally (if still available):
/glade/p/cesmdata/cseg/runs/cesm2_0/$CASE

On github:
https://github.com/NCAR/amwg_dev/tree/$CASE

**Sandbox:**
Locally (if still available):
 /glade/work/hannay/cesm_tags/cesm2_3_alpha13b
 
On github:
```
git clone https://github.com/ESCOMP/cesm cesm2_3_alpha13b
cd cesm2_3_alpha13b
git checkout  cesm2_3_alpha13b
./manage_externals/checkout_externals -o
```
**Diagnostics:**
AMWG diags (if available)
[https://webext.cgd.ucar.edu/BLT1850/$CASE/atm/](https://webext.cgd.ucar.edu/BLT1850/$CASE/atm/)

**Contacts:**

**Comment by cecilehannay** [comment]
see run #367
