### ISSUE TITLE
Runs for ERF 

### ISSUE THREAD

**Issue by cmcclus** [NCAR/amwg_dev#368]
### Description of the run

Two AMIP-like (F2000climo) 10 year runs are needed to assess the effective radiative forcing from aerosol–cloud interactions (ERF_aci). Differencing the TOA radiative fluxes between a simulation with historical aerosol emissions and preindustrial aerosol emissions gives an estimate of the ERF_aci (e.g., Bellouin et al. https://doi.org/10.1029/2019RG000660, Smith et al. https://doi.org/10.5194/acp-20-9591-2020).

Two AMIP-like (F2000climo) 10 year runs are needed using the latest development baseline:
1. AMIP-like with historical aerosol emissions
2. AMIP-like with with preindustrial emissions 

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

Christina McCluskey & Brian Medeiros 

### Any other relevant information

Enter relevant info

**Comment by adamrher** [comment]
Excellent idea @cmcclus. I just sent Ben a script from Trude that sets up these aerosol sensitivity experiments. Do you want me to forward that along or do you already know how to do this?

**Comment by cecilehannay** [comment]
I can run these or help Christina to set them if she wants to do herself.  On Aug 16, 2023, at 5:43 PM, Adam Herrington ***@***.***> wrote:﻿
Excellent idea @cmcclus. I just sent Ben a script from Trude that sets up these aerosol sensitivity experiments. Do you want me to forward that along or do you already know how to do this?

**Comment by cmcclus** [comment]
@adamrher - yes, please include me with aerosol-related questions/tests. When you say "aerosol sensitivity experiments", do you mean the two different climate simulations (pre-industrial vs. present day)? 

@cecilehannay - I wonder if we could include this as a regularly scheduled simulation set to run each time you have a new baseline. I'd like to keep an eye on ERF on a regular basis, if possible!

**Comment by cecilehannay** [comment]
We certainly can include this as a regular simulation. 
During CAM5 and CAM6 development,I was doing regular simulation pre-industrial/present day aerosol for Andrew. It is a good suggestion to restart doing this

**Comment by swrneale** [comment]
@cmcclus this is great for you to take up this analysis since this is your area of expertise :) and we really need to keep an eye on this as @cecilehannay said

**Comment by adamrher** [comment]
In case it's helpful, here's the email I rec'd from Trude:

> Hi Adam
>
>I have the scripts here: 
>
>/glade/campaign/cgd/projects/ppe/cam_ppe/rerun_PPE_250
>
>If you look at the difference between build_ppe_CAM_cases_PD.py and build_ppe_CAM_cases_PI.py, you will see how to specify the 1850 aerosols.

**Comment by adamrher** [comment]
In addition to running the ERF test with the current code base, can we also run it for CESM2.1 CAM6 (official CESM2), so we have a benchmark.

**Comment by cmcclus** [comment]
I agree, @adamrher and just mentioned this to Cecile before seeing your note. If there is a big difference, I will likely want the same simulation set for some other tags, but let's see where it is now. 

I'll be attending the CAM7 meetings coming on up to be more in tune with model changes to request the ERF simulations set when there is reason to worry about changes to the aerosol-cloud-interactions.

**Comment by cecilehannay** [comment]
There is no FLT compset for 2000 or 2000climo. I am setting the run to run 2000 but it will be mix of 2000 and 2000climo datasets.

**Comment by cecilehannay** [comment]
See #388 and #389
