### ISSUE TITLE
Run with microp_aero_wsub_min   =   0.0

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/amwg_dev#369]
### Description of the run

Same as #366 (so called coupled run "36") with
```
microp_aero_wsub_min            =   0.2->0.
```

@adamrher, @PeterHjortLauritzen, @JulioTBacmeister: confrim this is what you want.   

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

Contact information

### Any other relevant information

Enter relevant info

**Comment by adamrher** [comment]
Thanks, Cecile. I was just going to submit this run request.

**Comment by cecilehannay** [comment]
see: #370
