### ISSUE TITLE
run latest FLTHIST with dust tuning

### ISSUE THREAD

**Issue by tilmes** [NCAR/amwg_dev#378]
### Description of the run

we want to repeat the latest https://github.com/NCAR/amwg_dev/issues/353
with changes in dust emission:
Change: dust_emis_fact         = 0.80D0 
to dust_emis_fact         = 1.1

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

Contact information

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
See: #381
