### ISSUE TITLE
One line description for your simulation request

### ISSUE THREAD

**Issue by cacraigucar** [NCAR/amwg_dev#382]
### Description of the run

5 year run, FHIST, 1 degree to test changes in https://github.com/ESCOMP/CMEPS/pull/394

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

cacraig@ucar.edu

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
Running as #384
