### ISSUE TITLE
modify ice cloud fraction algorithm 

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#387]
**Description:**

Following discussions with Thomas, I'd like to try NorESMs modifications to the ice cloud fraction algorithm. It is a blend of iceopt=4 and iceopt=5, where we have been using just iceopt=5. It should boost LWCF, as it retains larger ice fractions in the small ice concentration regime. I'd use the modifier "iceopt45" to denote this run.

Same as coupled run 38 (https://github.com/NCAR/amwg_dev/issues/370), but with the following SourceMods:

```
/glade/u/home/aherring/src/cam6_3_115/usr_src/iceopt/cldfrc2m.F90
```
___
**Case directory:**
Locally (if still available):
/glade/p/cesmdata/cseg/runs/cesm2_0/$CASE

On github:
https://github.com/NCAR/amwg_dev/tree/$CASE
___
**Sandbox:**
Locally (if still available):
 /glade/work/hannay/cesm_tags/cesm2_3_alpha16b
 
On github: https://github.com/ESCOMP/cesm/tree/cesm2_3_alpha16b
___
**Diagnostics:**
Diags (if available)

[https://webext.cgd.ucar.edu/BLT1850/$CASE/](https://webext.cgd.ucar.edu/BLT1850/$CASE/)
___
**Output:**
Output (if still available):
/glade/derecho/scratch/hannay/archive/$CASE/
___
**Contacts:**
@cecilehannay
___
**Extra details:**

**Comment by cecilehannay** [comment]
See run: #391
