### ISSUE TITLE
Coupled test with CLUBB taus code ON

### ISSUE THREAD

**Issue by bstephens82** [NCAR/amwg_dev#394]
### Description of the run

This would be a new coupled test using @bstephens82's latest tuning with CLUBB's taus code turned on.

### Suffix in the casename

Suffix

### Namelist modifications

ncdata = '/glade/work/aherring/grids/vertical-res/L58/FWsc_ne30pg3_58L_GRID_48_taperstart10km_lowtop_BL10_v3_beta1p75_Top_43km.nc'

interpolate_output = .true.,.true.
interpolate_nlat   = 192,192
interpolate_nlon   = 288,288

!----non-CLUBB parameters
dust_emis_fact         = 0.80D0
seasalt_emis_scale=1.5
micro_mg_dcs=0.00065
micro_mg_vtrmi_factor=1.25
microp_aero_wsubi_scale=1.0
microp_aero_wsub_scale = 0.01
zmconv_dmpdz=-0.0005
cldfrc_dp2=750

!----CLUBB parameters
clubb_C1                           =    0.80000000000000
clubb_C1b                          =    0.80000000000000
clubb_C1c                          =   0.750000000000000
clubb_C2rt                         =    1.00000000000000
clubb_C2thl                        =    1.00000000000000
clubb_C2rtthl                      =    1.00000000000000
clubb_C4                           =    1.00000000000000
clubb_c_uu_shr                     =   0.1
clubb_C_uu_buoy                    =   0.000000000000000E+000
clubb_C6rt                         =    1.00000000000000
clubb_C6rtb                        =    1.00000000000000
clubb_C6rtc                        =   0.500000000000000
clubb_C6thl                        =    1.00000000000000
clubb_C6thlb                       =    1.00000000000000
clubb_C6thlc                       =   0.500000000000000
clubb_c7  = 0.1
clubb_C7b                          =   0.700000000000000
clubb_C7c                          =   0.500000000000000
clubb_C8                           =   0.80000000000
clubb_C8b                          =   0.000000000000000E+000
clubb_C11                          =   0.500000000000000
clubb_C11b                         =   0.800000000000000
clubb_C11c                         =   0.850000000000000
clubb_C12                          =    1.00000000000000
clubb_C14                          =    0.80000000000000
clubb_C_wp3_pr_turb                =    1.00000000000000
clubb_C_wp2_splat                  =   0.000000000000000E+000
clubb_C6rt_Lscale0                 =    14.0000000000000
clubb_C6thl_Lscale0                =    14.0000000000000
clubb_C7_Lscale0                   =   0.850000000000000
clubb_wpxp_L_thresh                =    100.000000000000
clubb_c_K                          =   0.200000000000000
clubb_c_K1                         =    1.00000000000000
clubb_nu1                          =    10.0000000000000
clubb_c_K2                         =   0.100000000000000
clubb_nu2                          =    1.00000000000000
clubb_c_K6                         =   0.375000000000000
clubb_nu6                          =    5.00000000000000
clubb_c_K8                         =    10.0000000000000
clubb_nu8                          =    20.0000000000000
clubb_c_K9                         =   0.250000000000000
clubb_nu9                          =    20.0000000000000
clubb_nu10                         =   0.000000000000000E+000
clubb_c_K_hm                       =   0.750000000000000
clubb_c_K_hmb                      =   0.750000000000000
clubb_K_hm_min_coef                =   0.100000000000000
clubb_nu_hm                        =    1.50000000000000
clubb_slope_coef_spread_DG_means_w =    21.0000000000000
clubb_pdf_component_stdev_factor_w =    1.00000000000000
clubb_coef_spread_DG_means_rt      =   0.800000000000000
clubb_coef_spread_DG_means_thl     =   0.800000000000000
clubb_gamma_coef                   =   0.250000000000000
clubb_gamma_coefb                  =   0.320000000000000
clubb_gamma_coefc                  =    1.20000000000000
clubb_mu                           =   5.000000000000000E-004
clubb_beta                         =    2.00000000000000
clubb_lmin_coef                    =   0.100000000000000
clubb_omicron                      =   0.500000000000000
clubb_zeta_vrnce_rat               =   0.000000000000000E+000
clubb_upsilon_precip_frac_rat      =   0.550000000000000
clubb_lambda0_stability_coef       =   3.000000000000000E-002
clubb_mult_coef                    =    1.00000000000000
clubb_taumin                       =    90.0000000000000
clubb_taumax                       =    3600.00000000000
clubb_Lscale_mu_coef               =    2.00000000000000
clubb_Lscale_pert_coef             =   0.100000000000000
clubb_alpha_corr                   =   0.150000000000000
clubb_Skw_denom_coef               =   0.000000000000000E+000
clubb_c_K10                        =   0.300000000000000
clubb_c_K10h                       =   0.350000000000000
clubb_thlp2_rad_coef               =    1.00000000000000
clubb_thlp2_rad_cloud_frac_thresh  =   0.100000000000000
clubb_up2_sfc_coef                 =    2.00000000000000
clubb_Skw_max_mag                  =    4.50000000000000
clubb_C_invrs_tau_bkgnd            =    1.10000000000000
clubb_C_invrs_tau_sfc              =   5.000000000000000E-002
clubb_C_invrs_tau_shear            =   0.220000000000000
clubb_C_invrs_tau_N2               =   0.300000000000000
clubb_C_invrs_tau_N2_wp2           =   0.100000000000000
clubb_C_invrs_tau_N2_xp2           =   0.000000000000000E+000
clubb_C_invrs_tau_N2_wpxp          =    2.00000000000000
clubb_C_invrs_tau_N2_clear_wp3     =    2.00000000000000
clubb_C_invrs_tau_wpxp_Ri          =    3.00000000000000
clubb_C_invrs_tau_wpxp_N2_thresh   =   3.500000000000000E-004
clubb_xp3_coef_base                =   0.250000000000000
clubb_xp3_coef_slope               =   1.000000000000000E-002
clubb_altitude_threshold           =    150.000000000000
clubb_rtp2_clip_coef               =   0.500000000000000
clubb_Cx_min                       =   0.330000000000000
clubb_Cx_max                       =   0.950000000000000
clubb_Richardson_num_min           =   0.250000000000000
clubb_Richardson_num_max           =    400.000000000000
clubb_a3_coef_min                  =    1.60000000000000
clubb_a_const                      =   1.6000000000000
clubb_c_wp2_pr_dfsn = 0.
clubb_c_wp3_pr_dfsn = 0.
clubb_c_wp3_pr_tp = 0.

!-----CLUBB flags
clubb_l_use_precip_frac =  .true.
clubb_l_predict_upwp_vpwp =  .true.
clubb_l_min_wp2_from_corr_wx =  .false.
clubb_l_min_xp2_from_corr_wx =  .false.
clubb_l_C2_cloud_frac =  .false.
clubb_l_diffuse_rtm_and_thlm =  .false.
clubb_l_stability_correct_Kh_N2_zm =  .false.
clubb_l_calc_thlp2_rad =  .true.
clubb_l_upwind_xpyp_ta =  .true.
clubb_l_upwind_xm_ma =  .true.
clubb_l_uv_nudge =  .false.
clubb_l_rtm_nudge =  .false.
clubb_l_tke_aniso =  .true.
clubb_l_vert_avg_closure =  .false.
clubb_l_trapezoidal_rule_zt =  .true.
clubb_l_trapezoidal_rule_zm =  .true.
clubb_l_call_pdf_closure_twice =  .true.
clubb_l_standard_term_ta =  .false.
clubb_l_partial_upwind_wp3 =  .false.
clubb_l_godunov_upwind_wpxp_ta =  .false.
clubb_l_godunov_upwind_xpyp_ta =  .false.
clubb_l_use_cloud_cover =  .false.
clubb_l_diagnose_correlations =  .false.
clubb_l_calc_w_corr =  .false.
clubb_l_const_Nc_in_cloud =  .false.
clubb_l_fix_w_chi_eta_correlations =  .true.
clubb_l_stability_correct_tau_zm =  .false.
clubb_l_damp_wp2_using_em =  .true.
clubb_l_do_expldiff_rtm_thlm =  .false.
clubb_l_Lscale_plume_centered =  .false.
clubb_l_diag_Lscale_from_tau =  .true.
clubb_l_use_C7_Richardson =  .true.
clubb_l_use_C11_Richardson =  .false.
clubb_l_use_shear_Richardson =  .false.
clubb_l_brunt_vaisala_freq_moist =  .false.
clubb_l_use_thvm_in_bv_freq =  .false.
clubb_l_rcm_supersat_adj =  .true.
clubb_l_damp_wp3_Skw_squared =  .true.
clubb_l_prescribed_avg_deltaz =  .false.
clubb_l_lmm_stepping =  .false.
clubb_l_e3sm_config =  .false.
clubb_l_vary_convect_depth = .false.
clubb_l_use_tke_in_wp3_pr_turb_term =  .false.
clubb_l_use_tke_in_wp2_wp3_K_dfsn =  .false.
clubb_l_smooth_Heaviside_tau_wpxp =  .false.
clubb_l_enable_relaxed_clipping =  .true.
clubb_l_linearize_pbl_winds =  .false.
clubb_l_mono_flux_lim_thlm =  .true.
clubb_l_mono_flux_lim_rtm =  .true.
clubb_l_mono_flux_lim_um =  .true.
clubb_l_mono_flux_lim_vm =  .true.
clubb_l_mono_flux_lim_spikefix =  .true.

### Source modifications

/glade/derecho/scratch/stepheba/117.f2c.taus_new_base_latest_mods14/SourceMods/src.cam/mixing_length.F90

-----------------------------
In my local CAM repo, I have added ALL CLUBB parameters and flags as namelist parameters so they can all be modified from the namelist.  So many of the namelist options given above will not work without modifications to the namelist_definitions file, etc., and clubb_intr.F90.  It is possible it might be necessary to use my local CLUBB directory as well.  Here are paths to my modified namelist files and clubb_intr.F90, I am hoping clubb_intr.F90 will compile successfully but I'm not sure offhand.

/glade/u/home/stepheba/CAM/bld/build-namelist
/glade/u/home/stepheba/CAM/bld/namelist_files/namelist_defaults_cam.xml
/glade/u/home/stepheba/CAM/bld/namelist_files/namelist_definition.xml

/glade/u/home/stepheba/CAM/src/physics/cam/clubb_intr.F90

It may be necessary to change to the following in Externals_CAM.cfg:
~~~
[clubb]
local_path = src/physics/clubb
protocol = svn
repo_url = https://github.com/bstephens82/clubb_src/tags/
tag = bstephens82.clubb_src.aa1d359
required = True
~~~

### Sandbox

Requested sandbox or tag

### Contact info

@bstephens82, @vlarson, @JulioTBacmeister 

### Any other relevant information

In my own coupled run, I used the beta14 CESM tag, with B1850MOM and ne30pg3_t232.

**Comment by adamrher** [comment]
I am wondering for this first run with tau's code, that we use the "non-clubb" parameters that we are already using in the coupled runs (either #37 or #38). And if that simulation is seriously degraded, that we *then* turn on Ben's non-clubb parameters. Or we could do the two runs in parallel.

**Comment by bstephens82** [comment]
> I am wondering for this first run with tau's code, that we use the "non-clubb" parameters that we are already using in the coupled runs (either #37 or #38). And if that simulation is seriously degraded, that we _then_ turn on Ben's non-clubb parameters. Or we could do the two runs in parallel.

I would be curious to see what they look like with those parameters reverted, but those were some of the main ones I was tweaking so I think we should run them in parallel at least.

**Comment by adamrher** [comment]
I see. I guess I didn't appreciate that the non-clubb parameters are crucial ingredients to your recipe. I vote for parallel, mostly because I'm a little concerned about the scientific justification for ```microp_aero_wsub_scale = 0.01```. I think we need to see that parallel run in order to sell such a small value of wsub_scale.

**Comment by adamrher** [comment]
I just spoke with Cecile. I'm going to open a second run request for this parallel simulation.

**Comment by bstephens82** [comment]
> I am having troubles to build:
> 
> ```
> 
> /glade/p/cesmdata/cseg/runs/cesm2_0/b.e23_alpha16b.BLT1850.ne30_t232.043/SourceMods/src.cam/mixing_length.F90
> 
> ```
> 
> See in:
> 
> ```
> 
>  /glade/derecho/scratch/hannay/b.e23_alpha16b.BLT1850.ne30_t232.043/bld/atm.bldlog.230901-132852
> 
> ```
> 
> 
> 
> 
> 
> DO you think that changing Externals.cfg to:
> 
> ```
> 
> [clubb]
> 
> local_path = src/physics/clubb
> 
> protocol = svn
> 
> repo_url = https://github.com/bstephens82/clubb_src/tags/
> 
> tag = bstephens82.clubb_src.aa1d359
> 
> required = True
> 
> ```
> 
> will help? 

I would try this yes.

**Comment by cecilehannay** [comment]
@bstephens82:

I tried to set:
```
[clubb]
local_path = src/physics/clubb
protocol = svn
repo_url = https://github.com/bstephens82/clubb_src/tags/
tag = bstephens82.clubb_src.aa1d359
required = True
```

But I am having issues and it looks like that repo doesn't exist. Jim tried to help me. He thinks that either you had a typo in the repo name or it's private which is why I cannot access it.

**Comment by bstephens82** [comment]
@cecilehannay sorry about that yes it was private. It should be public now.

**Comment by cecilehannay** [comment]
Thanks for changing permissions. 

I am still having issues with:
```
./../manage_externals/checkout_externals -e Externals_CAM.cfg
```
I am getting the following error:
```
Processing externals description file : Externals_CAM.cfg (/glade/work/hannay/cesm_tags/cesm2_3_alpha16b_taus/components/cam)
Processing externals description file : Externals_HCO.cfg (/glade/work/hannay/cesm_tags/cesm2_3_alpha16b_taus/components/cam/src/hemco)
Processing externals description file : .gitmodules (/glade/work/hannay/cesm_tags/cesm2_3_alpha16b_taus/components/cam/src/hemco/HEMCO)
Checking local status of required & optional components: chem_proc, carma, cosp2, clubb, silhs, pumas, pumas-frozen, ali_arms, atmos_phys, atmos_cubed_sphere, mpas, hemco, hemco_src, docs/source/geos-chem-shared-docs, 
Checking out externals: chem_proc, atmos_phys, atmos_cubed_sphere, mpas, hemco, Processing externals description file : Externals_HCO.cfg (/glade/work/hannay/cesm_tags/cesm2_3_alpha16b_taus/components/cam/src/hemco)
Processing externals description file : .gitmodules (/glade/work/hannay/cesm_tags/cesm2_3_alpha16b_taus/components/cam/src/hemco/HEMCO)
Checking out externals: hemco_src, Processing externals description file : .gitmodules (/glade/work/hannay/cesm_tags/cesm2_3_alpha16b_taus/components/cam/src/hemco/HEMCO)
Checking out externals: docs/source/geos-chem-shared-docs, 

ali_arms, carma, clubb, ERROR:root:Command '['svn', 'switch', '--quiet', 'https://github.com/bstephens82/clubb_src/tags/bstephens82.clubb_src.aa1d359']' returned non-zero exit status 1.
ERROR:root:Failed with output:
    svn: E170009: 'svn switch' does not support switching a working copy to a different repository
    svn: E170009: Repository UUID '8af1e365-9f2d-448a-5552-ce57b7db7bff' doesn't match expected UUID '5178b1a5-72e8-6ac6-cb9c-ce57b7db7bff'

ERROR: In directory
    /glade/work/hannay/cesm_tags/cesm2_3_alpha16b_taus/components/cam/src/physics/clubb
Process did not run successfully; returned status 1:
    svn switch --quiet https://github.com/bstephens82/clubb_src/tags/bstephens82.clubb_src.aa1d359
See above for output from failed command.

ERROR:root:Failed with output:
    svn: E170009: 'svn switch' does not support switching a working copy to a different repository
    svn: E170009: Repository UUID '8af1e365-9f2d-448a-5552-ce57b7db7bff' doesn't match expected UUID '5178b1a5-72e8-6ac6-cb9c-ce57b7db7bff'
```

**Comment by bstephens82** [comment]
Have you tried deleting the CLUBB folder (src/physics/clubb) and then rerunning the externals?

**Comment by cecilehannay** [comment]
See run: #398
