### ISSUE TITLE
Coupled test with CLUBB taus code ON (but w/ #37 non-clubb tunings)

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#395]
**Description:**

Same as https://github.com/NCAR/amwg_dev/issues/394, but replacing the non-clubb tunings:

!----non-CLUBB parameters
dust_emis_fact = 0.80D0
seasalt_emis_scale=1.5
micro_mg_dcs=0.00065
micro_mg_vtrmi_factor=1.25
microp_aero_wsubi_scale=1.0
microp_aero_wsub_scale = 0.01
zmconv_dmpdz=-0.0005
cldfrc_dp2=750

With those in coupled run 37 (https://github.com/NCAR/amwg_dev/issues/367). That is, we don't want to use the above "non-CLUBB parameters". I expect this run to be out to lunch, but I want to see the impact of just the tau's code, on top of our existing coupled runs.
___
**Case directory:**
Locally (if still available):
/glade/p/cesmdata/cseg/runs/cesm2_0/$CASE

On github:
https://github.com/NCAR/amwg_dev/tree/$CASE
___
**Sandbox:**
Locally (if still available):
 /glade/work/hannay/cesm_tags/cesm2_3_alpha16b
 
On github: https://github.com/ESCOMP/cesm/tree/cesm2_3_alpha16b
___
**Diagnostics:**
Diags (if available)

[https://webext.cgd.ucar.edu/BLT1850/$CASE/](https://webext.cgd.ucar.edu/BLT1850/$CASE/)
___
**Output:**
Output (if still available):
/glade/derecho/scratch/hannay/archive/$CASE/
___
**Contacts:**
@cecilehannay @bstephens82
___
**Extra details:**

**Comment by cecilehannay** [comment]
Differences between 
- 37 non-clubb tunings
- and Ben's tuning: 

```
clubb_gamma_coef       = 0.25->0.3
clubb_gamma_coefb      = 0.32->0.3

micro_mg_dcs           = 650->500.D-6
micro_mg_vtrmi_factor  = 1.25->1.0
microp_aero_wsub_scale = 0.01->0.25

cldfrc_dp2             =  750->500.0D0 
zmconv_dmpdz           =  -1.0E-3 
```
Technically, `clubb_gamma_coef` and `clubb_gamma_coefb` are clubb tuning but I didn't know if we wanted to set these as in `37` or as in Ben's run.

**Comment by adamrher** [comment]
Lets use the clubb_gamma values in 37 (0.3)

**Comment by cecilehannay** [comment]
See run #399
