### ISSUE TITLE
Increase Zhang-McFarlane number of cin levels from 1 to 2

### ISSUE THREAD

**Issue by swrneale** [NCAR/amwg_dev#397]
### Description of the run

The ZM scheme only allows one layer of -ve buoyancy in. a column before terminating at the convective top. This was introduced in CAM6 and generally produces too shallow convection. However,  now it seems this is too limiting given the increase to L58 and the moderation of parcel buoyancy properties by the ZM2 parcel mixing changes. Relax this limit to 2 (-ve buoyancy levels). For context, this value was 5 prior to CAM6. 

### Suffix in the casename

_numcin2

### Namelist modifications

zmconv_num_cin=2

### Source modifications

None

### Sandbox

Requested sandbox or tag

### Contact info

@swrneale @JulioTBacmeister @PeterHjortLauritzen @adamrher 

### Any other relevant information

Enter relevant info

**Comment by adamrher** [comment]
What should the baseline be? I'm thinking either coupled run 37 or 38. We can chat more about this tmrw.

**Comment by cecilehannay** [comment]
We don't have a F baseline for those. Let's talk tomorrow and decide which baseline we want and I can do a new F baseline with that run

**Comment by swrneale** [comment]
It would be good to have a new clean baseline as I would also like to test the dynamic plume changes we talked about Friday. And I could see us doing other ZM sensitivity tests along the way. Thanks!

**Comment by cecilehannay** [comment]
I fully agrée. It was exactly what I was suggesting in my previous post (having a clean baseline). Sorry if it was not clear

**Comment by adamrher** [comment]
If we are doing this in coupled, then there are plenty of baselines to choose from, saving us from have to do another run. But if this work is better explored in an F-case, then I agree we probably need a new baseline.

**Comment by swrneale** [comment]
I would prefer FHIST, as the B cases might be too difficult to interpret with feedbacks, at least initially.

**Comment by cecilehannay** [comment]
The only FHIST case I have is 33. But I can do a new baseline.

**Comment by cecilehannay** [comment]
See: #400
