### ISSUE TITLE
New FMTHIST baseline

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/amwg_dev#418]
### Description of the run

New FMTHIST baseline with cam6_3_132 to approximately match coupled run 52 (https://github.com/NCAR/amwg_dev/issues/413)

Note 1: there is a CMEPS change that was not in coupled run 52 (https://github.com/ESCOMP/CMEPS/pull/394)
Note 2: dust change from Simone (see namelist modifications) that was not in coupled run 52

### Suffix in the casename

f.cam6_3_132.FMTHIST_ne30.001

### Namelist modifications

dust_emis_fact = 1.3

### Sandbox

/glade/work/hannay/cesm_tags/cam6_3_132

### Contact info

@JulioTBacmeister @adamrher

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
See run #423
