### ISSUE TITLE
test impact of additional thlm and qtm diffusion

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#422]
### Description of the run

One aspect that's new to the clubb externals brought into cam6_3_059, was that it turned off additional diffusion of thlm and qtm. That is, in our old externals, clubb not only advanced thlm and rtm due to the prognostic turbulent fluxes, it was additionally diffusing thlm and rtm using the diffusion coefficient it uses for tracers.

I've found that this flag has a significant impact on PRECL and Tropical variability. Turning it on tends to increase PRECL and increase Kelvin wave activity. Therefore I'd suggest experimenting with turning this on:

```
clubb_l_do_expldiff_rtm_thlm = .true.
```

Not clear whether whether we should experiment with this in FLTHIST of BLT1850. Let's discuss!

@PeterHjortLauritzen @swrneale @JulioTBacmeister @bstephens82

### Suffix in the casename

Suffix

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@adamrher

### Any other relevant information

Enter relevant info

**Comment by bstephens82** [comment]
Can you say more about the motivation for testing it?  @vlarson has said it didn't have a strong theoretical justification so I'm just wondering what the goal is. Are we considering turning it back on?

**Comment by adamrher** [comment]
I understand that it's not ideal from a theoretical perspective, but my experience doing revert experiments with clubb+mf is that it improves aspects of the climatology. It would be good for everyone to understand the implications of turning this off since it seems to have slipped under the radar that this thing got turned off (or that it was ever on).
