### ISSUE TITLE
repeat 54 but backing out the 

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/amwg_dev#424]
### Description of the run

In 42 we added a change 
```
/glade/u/home/aherring/src/cam6_3_115/usr_src/iceopt/cldfrc2m.F90
```
This used NorESMs modifications to the ice cloud fraction algorithm. It is a blend of iceopt=4 and iceopt=5, where we have been using just iceopt=5. 

This change is now part of the trunk. 

IN the present we would like to back off this change. 

### Suffix in the casename

Suffix

### Namelist modifications

same as 54

### Source modifications

same as 54 + reverting to the old cldfrc2m.F90

### Sandbox

same as 54

### Contact info

@PeterHjortLauritzen, @adamrher  

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
@adamrher : could I just use the old cldfrc2m.F90 or did I need an updated version?

**Comment by adamrher** [comment]
@cecilehannay it is now a namelist, so just set 

```
cldfrc2m_do_avg_aist_algs = .false.
```

**Comment by cecilehannay** [comment]
Run started as https://github.com/NCAR/amwg_dev/issues/425
