### ISSUE TITLE
new coupled run - 46 with the new code base

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#431]
### Description of the run

Run https://github.com/NCAR/amwg_dev/issues/402 but with the new code base. Please don't specify the runoff mapping files as they aren't done correctly in that run. Only CAM namelists need to be changed.

### Suffix in the casename

Suffix

### Namelist modifications

```
microp_aero_wsub_scale  = 0.25
cldfrc2m_do_avg_aist_algs = .false.
cldfrc2m_qist_min = 1.e-7
```

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@adamrher 

### Any other relevant information

Enter relevant info

**Comment by adamrher** [comment]
@PeterHjortLauritzen @JulioTBacmeister @cecilehannay I'm not so sure how useful this run is. It's no different than the *corrected* run 58 (now called 61), but with wsub_factor=0.375->0.25. And no one has shown that the existing run 46 this is intended to replicate in the new code base is any better than our current baseline on the current code base (54). We are just trying to look into this idea that the ice fraction mods are negatively impacting el nino and so this run request doesn't add to that and vote to scrap it.

**Comment by PeterHjortLauritzen** [comment]
OK lets scrap!

**Comment by adamrher** [comment]
OK. We'll hold off on this until we see what 61 looks like --- It may be too cold, in which case we will need to lower wsub_factor=0.375->0.25, in which case that's identically run 46 and what we're requesting here.

**Comment by cecilehannay** [comment]
There is also a difference in the `dust_emis_fact=0.8->1.3` between 46 and 61 although I don't think that matters too much.
