### ISSUE TITLE
new coupled run - re-do 58 correctly

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#432]
### Description of the run

I messed up and didn't setup https://github.com/NCAR/amwg_dev/issues/425 correctly, so request to re-do. I forget to have you revert the cldfrc2m_qist_min.

### Suffix in the casename

Suffix

### Namelist modifications

```
cldfrc2m_do_avg_aist_algs = .false.
cldfrc2m_qist_min = 1.e-7
```

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

Contact information

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
This coupled run "61": https://github.com/NCAR/amwg_dev/issues/434
