### ISSUE TITLE
new coupled run - 54 but with added clubb diffusion

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#433]
### Description of the run

Run https://github.com/NCAR/amwg_dev/issues/420 but with added clubb diffusion (via user_nl_cam). This will perturb RESTOM quite a bit, so let's just do 10 years and see where we are at.

### Suffix in the casename

Suffix

### Namelist modifications

```
clubb_l_do_expldiff_rtm_thlm = .true.
```

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@adamrher

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
This was run in #435 (coupled run "62")
