### ISSUE TITLE
new coupled run - #63 + increase clubb_c8

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#438]
### Description of the run

Run 63 (https://github.com/NCAR/amwg_dev/issues/436) but with clubb_C8 = 4.2->4.5

This is a good plan B fall back. 

### Suffix in the casename

Suffix

### Namelist modifications

```
clubb_C8=4.5
```

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@adamrher @PeterHjortLauritzen @JulioTBacmeister 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
Coupled run "66" (#441)
