### ISSUE TITLE
new coupled run - experiment w/ 4X increase in rain re-evaporation

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#439]
### Description of the run

Same as 54 (https://github.com/NCAR/amwg_dev/issues/420) but with ZM re-evaporation efficiency over ocean increased zmconv_ke = 5.E-6 -> 2.E-5

### Suffix in the casename

Suffix

### Namelist modifications

```
zmconv_ke = 2.E-5
```

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@adamrher @PeterHjortLauritzen @JulioTBacmeister 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
See run #442
