### ISSUE TITLE
new coupled run - 66 w/ new limiter for vapor deps on snow

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#444]
### Purpose of the run

Test new PUMAS limiter in coupled run. Needed to green light bringing this onto the trunk. Should only need 10 years.

### Description of the run

Use run 66 as a baseline https://github.com/NCAR/amwg_dev/issues/441. Only need a SourceMod to activate new limiter.

### Suffix in the casename

limvapdeps

### Namelist modifications

Namelist

### Source modifications

```
/glade/scratch/aherring/cam6_3_097_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_1800pes_231128_mg2_limvapdeps_Nx2yrs/SourceMods/src.cam/micro_pumas_v1.F90
```

### Sandbox

Requested sandbox or tag

### Contact info

@adamrher @PeterHjortLauritzen @Katetc @cacraigucar

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
See #445
