### ISSUE TITLE
new coupled run 2 - run 67 but w/ 2X increase in zm re-evap

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#447]
### Purpose of the run

Same as 67 (https://github.com/NCAR/amwg_dev/issues/442) but set zm re-evap set to 2X:

```
zmconv_ke = 5.E-6 -> 1.E-5
```

### Description of the run

zm re-evap set to 2X

### Suffix in the casename

Suffix

### Namelist modifications

```
zmconv_ke = 5.E-6 -> 1.E-5
```

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@adamrher @JulioTBacmeister @PeterHjortLauritzen 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
see: https://github.com/NCAR/amwg_dev/issues/448
