### ISSUE TITLE
New baseline combining 61 + 64 + 68

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/amwg_dev#449]
### Purpose of the run

The purpose of the simulation is to create a new baseline with all the mods that we expect will go on the trunk:
- revert mods to the ice cloud fraction as in 61 (#434)
- add gustiness as in 64 (#440)
- Limiter for new vapor deposition on snow in PUMAS as in 68 (#445)

### Description of the run

Enter Description

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@adamrher @JulioTBacmeister @PeterHjortLauritzen @megandevlan @swrneale

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
Hi @PeterHjortLauritzen 

When you said we want to combine 61 + 64 + 68, I assume that:
- **we only want the PUMAS Sourcemods** from 68:
```
/glade/scratch/aherring/cam6_3_097_F2000dev_ne30pg3_ne30pg3_mg17_L58dev_1800pes_231128_mg2_limvapdeps_Nx2yrs/SourceMods/src.cam/micro_pumas_v1.F90
```
- **we don't want the extra tuning** that was in 68
```
clubb_l_do_expldiff_rtm_thlm = .true.
microp_aero_wsub_scale  = 1.0
clubb_C8 = 4.2->4.5
```
(These are the extra tuning for the "fallback")

**Comment by adamrher** [comment]
Correct.

**Comment by cecilehannay** [comment]
see: #451
