### ISSUE TITLE
Same as #64 but decrease Ugust magnitude

### ISSUE THREAD

**Issue by megandevlan** [NCAR/amwg_dev#450]
### Purpose of the run

Given the large ENSO impacts of the gust addition in https://github.com/NCAR/amwg_dev/issues/440, we want to try reducing the magnitude of the added gusts. 

### Description of the run

Same as https://github.com/NCAR/amwg_dev/issues/440, but with the ugust function having reduced coefficients (so the SourceMod for shr_flux_mod would change but nothing else). 

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods/src.drv: 
/glade/work/mdfowler/gust_cam7/cam_mods/cam7dev_july2023/shrMods_Cecile/cmeps_mods_reduceGust

### Sandbox

Requested sandbox or tag

### Contact info

@megandevlan, @swrneale, @PeterHjortLauritzen 
### Any other relevant information
~20 years should be enough to test

**Comment by cecilehannay** [comment]
As we are moving to a new baseline, I wonder if we should base this run on 70 (#451) instead of 64 (#440). What do you think?

**Comment by cecilehannay** [comment]
See: #453
