### ISSUE TITLE
new taus run: 074 + mods

### ISSUE THREAD

**Issue by bstephens82** [NCAR/amwg_dev#466]
### Purpose of the run

See whether we can get RESTOM back down with taus code.

### Description of the run

Same as #461 but with 

micro_mg_vtrmi_factor = 1.5
micro_mg_dcs = 0.0005

### Suffix in the casename

Suffix

### Namelist modifications

micro_mg_vtrmi_factor = 1.5
micro_mg_dcs = 0.0005

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@JulioTBacmeister @cecilehannay @adamrher @PeterHjortLauritzen @vlarson @zarzycki

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
This is run 76 (#471)
