### ISSUE TITLE
Cold branch test with "science optimized" SE-CSLAM dycore

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/amwg_dev#483]
### Purpose of the run

Science validate faster dycore + https://github.com/ESCOMP/CAM/issues/552 using cold branch (perhaps with spun-up ocean?)

### Description of the run

See purpose of run

### Suffix in the casename

sci_opt

### Namelist modifications

bnd_topo = "/glade/campaign/cgd/amp/pel/topo/files/se/ne30pg3_gmted2010_modis_bedmachine_nc3000_Laplace0100_noleak_20240117.nc"
se_hypervis_subcycle = 2

### Source modifications

Dycore source mods here:

/glade/campaign/cesm/cesmdata/cseg/runs/cesm2_0/f.cam6_3_132.FLTHIST_ne30.sci_opt_topo_gll.001/SourceMods/src.cam

### Sandbox

cam6_3_132

### Contact info

@cecilehannay @adamrher @JulioTBacmeister 

### Any other relevant information

Expected throughput from @jedwards4b:

```
 Model Cost:            4946.88   pe-hrs/simulated_year
 Model Throughput:        11.18   simulated_years/day
```

For comparison the current coupled runs are:

```
 Model Cost:            6371.85   pe-hrs/simulated_year
 Model Throughput:         8.20   simulated_years/day
```

**Comment by cecilehannay** [comment]
@jedwards4b: I am starting a BLT1850 run with that configuration. Do I need another pe_layout? 

Right now I am using: /glade/p/cesmdata/cseg/runs/cesm2_0/b.e23_alpha16g.BLT1850.ne30_t232.078/env_mach_pes.xml

**Comment by jedwards4b** [comment]
@cecilehannay Please try this layout - /glade/derecho/scratch/jedwards/PFS.ne30pg3_t232.BLT1850_v0c.derecho_intel.20240124_125358_ksodoz/env_mach_pes.xml 

Let me know when you have a timing file.

**Comment by cecilehannay** [comment]
See: #485
