### ISSUE TITLE
Rough topo coupled simulation (cold branch)

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/amwg_dev#488]
### Purpose of the run

Rougher topography has shown indications of improving precip in the polar regions and marginal improvements in stratospheric jets: 

https://github.com/NCAR/amwg_dev/issues/473

Therefore we would like to science evaluate rougher topography in coupled setup.

### Description of the run

Same as https://github.com/NCAR/amwg_dev/issues/485 but with rougher topography.

### Suffix in the casename

Suffix

### Namelist modifications

bnd_topo = "/glade/campaign/cgd/amp/pel/topo/files/se/ne30pg3_gmted2010_modis_bedmachine_nc3000_Laplace0050_noleak_20240116.nc"

### Source modifications

See https://github.com/NCAR/amwg_dev/issues/485

### Sandbox

See https://github.com/NCAR/amwg_dev/issues/485

### Contact info

@adamrher @cecilehannay @JulioTBacmeister @swrneale 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
see: #489
