### ISSUE TITLE
077 + optimized dycore + micro_mg_dcs = 0.0006

### ISSUE THREAD

**Issue by bstephens82** [NCAR/amwg_dev#490]
### Purpose of the run

Continue testing taus code.

### Description of the run

Same as #484 but with optimized dycore and one parameter change:
micro_mg_dcs 0.0005 --> 0.0006

### Suffix in the casename

Suffix

### Namelist modifications

micro_mg_dcs = 0.0006

### Source modifications

SourceMods

### Sandbox

alpha16g

### Contact info

@bstephens82 @JulioTBacmeister @adamrher @vlarson @zarzycki @PeterHjortLauritzen 

### Any other relevant information

Enter relevant info

**Comment by bstephens82** [comment]
@cecilehannay 077 is located here:
/glade/derecho/scratch/stepheba/b1850.076base.n2th1/

Hopefully it is straightforward to set up the new case based on this one.

**Comment by cecilehannay** [comment]
@PeterHjortLauritzen: do we want to use the rough topography?

**Comment by PeterHjortLauritzen** [comment]
I think we should wait until we have analyzed https://github.com/NCAR/amwg_dev/issues/489

**Comment by cecilehannay** [comment]
See run #491
