### ISSUE TITLE
4xco2 run

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/amwg_dev#492]
### Purpose of the run

Estimate ECS.

### Description of the run

I am working on starting the 4xCO2 run. We decide to base this run on the cold branch. 
I could based it from 75 (cold branch = #462) or 78 (cold branch + faster dycore = #485). 
- If we are satisfied that 78 produces similar climate to 75, I think it would be better to use that configuration as it faster and cheaper. 
Diags are [here](https://webext.cgd.ucar.edu/BLT1850/b.e23_alpha16g.BLT1850.ne30_t232.078/atm/b.e23_alpha16g.BLT1850.ne30_t232.078_2_21_vs_b.e23_alpha16g.BLT1850.ne30_t232.075_2_21/)
In the annual mean, it is the same climate.  In the lat/lon plots, there is some slight difference in SWCF in the South East Pacific stratocumulus but this might be variability.  
- But I can use 75 too if it is preferable to use the eact same configuration.. 

Thoughts?  (@PeterHjortLauritzen, @adamrher, @JulioTBacmeister, @brianpm, @swrneale)     

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

Contact information

### Any other relevant information

Enter relevant info

**Comment by adamrher** [comment]
> Unless anybody has objections please use 78

I object :). Run 80 more accurately reflects the direction of the tau's code, due it's more realistic cloud forcings, and so I would advocate using that for ECS.

**Comment by cecilehannay** [comment]
@adamrher: I object too :)

At the cesm meeting on Tuesday, we discussed:
- whether we want to use the cold branch or the warm branch for the 4xco2 run 
- and whether we want to use the 4xco2 files with 4 times annual cycle or create new 4xco2 files that preserved the annual cycle. 

We decided as a group to use the cold branch with the 4xco2 with 4x annual cycle. 

While I understand your point, I feel a bit uncomfortable to use the warm branch for the 4xo2 run as we explicitly decided to use the cold branch. So we want to change the plan, I would like to get the green light of @dlawrenncar, @klindsay28 and others. 
 
And I could do both if we have the computer time for that.

**Comment by adamrher** [comment]
I'm sorry @cecilehannay I misread Peter's comment. Yes, let's stick to the original plan just using the cold branch 78 for ECS. I mistakenly thought 78 was the warm branch.

**Comment by cecilehannay** [comment]
At Gunter's request (who needs this to work on diagnostics package), I am using:
```
glacier_region_behavior = 'single_at_atm_topo', 'virtual', 'virtual', 'virtual'
```
instead of:
```
glacier_region_behavior = 'single_at_atm_topo','virtual','virtual','multiple'
```
@olyson, @slevis-lmwg: I assume this won't change the climate, could you confirm?

**Comment by billsacks** [comment]
The 4th entry is Antarctica. Yes, this won't change the climate, and I think should be bit-for-bit unless there's a bug: it turns on calculations over 0-area glacier columns in Antarctica to be able to provide surface mass balance information for all elevation classes there.

**Comment by adamrher** [comment]
I may regret asking @billsacks, but this would only impact the SMB in CISM, provided CISM is active (either evolve or no-evolve), right? 0-area EC's have no impact on the SMB computed in CLM, since the sub-grid area weights being zero indicates there are no sub-grid elevations pertaining to that EC in a particular grid cell?

**Comment by adamrher** [comment]
Thanks Bill and Kate for clarifying the glacier_region_behavior namelist.

**Comment by cecilehannay** [comment]
See: #493
