### ISSUE TITLE
Background Kzz=1.0 in tropical UTLS

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/amwg_dev#51]
### Description of the run

A run with a region of background vertical diffusion 30S-30N and 500 to 50 hPa.   Repeats a previous run except diffusion is set to 1.0 m^2/s instead of 10.0 m^2/s

### Namelist modifications

None (hardwired)

### Source modifications

Spource mods are here:

/glade/u/home/juliob/nuclopt-02

Value of the diffusion is set in line 1281 of advance_clubb_core_module.F90. (That is the only difference between nuclopt and nuclopt-02)

### Sandbox

Use latest tag from cam_development branch

### Contact info

Julio Bacmeister (@JulioTBacmeister) requesting in consultation with @adamrher and @cecilehannay 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
Run started as f.e21.FWscHIST.ne30_L48_BL10_cam6_3_041_kzz1.hf.001
https://github.com/NCAR/amwg_dev/issues/54
