### ISSUE TITLE
New baseline with cam6_3_041

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/amwg_dev#52]
### Description of the run

New control with cam6_3_041. 

All the development is now on the main trunk.  We expect that the cam6_3_041 has the same climate as cam6_3_035.tphysac

### Namelist modifications

se_rsplit = 3 
se_nsplit = 2 
se_hypervis_subcycle = 4

From Peter: The out-of-the-box is for WACCM with a ~140km top that requires more stringent time-stepping (for stability) than the ~80km top model. Peter recommends manually setting the split values so that the model runs faster

### Source modifications

Will add source mods to output DQCORE.  

### Sandbox

cam6_3_041

### Any other relevant information

Proposed output: 

nhtfrq = 0, -24, -6, -3
interpolate_output = .true.,.true.,.true.,.true.
interpolate_nlat = 192,192,192,192
interpolate_nlon = 288,288,288,288

fincl1 = 'U','V','Q','T','PSL','OMEGA','PS','PRECC','PRECL','UTGWORO','VTGWORO',
'TS', 'TAUX','TAUY','TAUBLJX','TAUBLJY','TAUGWX','TAUGWY','FLNT','FLNS','FSNS','FSNT',
'LHFLX','SHFLX','TMQ','FLDS','FSDS','FSDSC','SWCF','LWCF','PRECSC','PRECSL', 'DTCOND','Z3', 'PSL'
'PBLH','ZMDT', 'ZMDT', 'STEND_CLUBB','RVMTEND_CLUBB',
'ZMDQ','CMFMC_DP','DPDLFLIQ','DPDLFICE','PCLDTOP','CLDTOP', 'KVH_CLUBB',
'DTCORE','DQCORE','PTEQ','DCQ','QTGW','CT_H2O','DCQ','MPDQ'

fincl2 = 'TROP_T', 'TROP_P', 'Q', 'T','U850','V850','U200','V200','PRECT','PRECC','PRECL','PBLH',
'OMEGA500','FLUT','Z500','T500','PS','PMID:I','TREFHTMN:M', 'TREFHTMX:X','TSMN:M', 'TSMX:X',
'PBLH','ZMDT', 'ZMDT', 'STEND_CLUBB','RVMTEND_CLUBB',
'PRECT','PRECL','U200','V200','U850','V850','FLUT','Z500','TREFHT','TS','CLDTOT','SWCF',
'LWCF','PS','PSL','TMQ','LHFLX','SHFLX','T500','OMEGA500','CLDLOW'

fincl3 = 'U:I','V:I','T:I', 'OMEGA:I','PS:I','PMID:I', 'OMEGA500','PRECT','U200','U850','FLUT','Q:I', 'ZMDT:I','ZMDQ:I','CMFMC_DP:I','DPDLFLIQ:I','DPDLFICE:I','PCLDTOP:I','CLDTOP:I' ,
'DTCORE:I','DQCORE:I','PTEQ:I','DCQ:I','QTGW:I','CT_H2O:I','DCQ:I','MPDQ:I'

fincl4 = 'PRECT','PRECC'

### Contact info

@cecilehannay 
@JulioTBacmeister 
@adamrher

**Comment by cecilehannay** [comment]
@PeterHjortLauritzen and @jtruesdal 

In the L58, we have been using the flags: 
 -cppdefs -Dwaccm_debug
in the CAM_CONFIG_OPTS

These don't come out of the box and we have been setting these for ever. I am not even sure what they do. Do you know?

We are now moving to cam6_3_041. I am not sure we still need the flags above. I thought I would ask you.

**Comment by cecilehannay** [comment]
@PeterHjortLauritzen 

Hi @PeterHjortLauritzen 

I have another question for you. 

In our L58 runs, we have been using:
se_rsplit            = 3
se_nsplit           = 2
se_hypervis_subcycle =  4

Now, we want to move to cam6_3_041. Out of the box, we get:  
se_rsplit            = 4
se_nsplit           = 5
se_hypervis_subcycle =  2

Do you want the out of the box values or the values we used in our previous L58 runs?

**Comment by cecilehannay** [comment]
@adamrher 

Please could you check you have all the output you want:

nhtfrq         =                  0, -24,  -6,  -3,  -1,   1, -24,-24

fincl1 = 'U','V','Q','T','PSL','OMEGA','PS','PRECC','PRECL','UTGWORO','VTGWORO',
         'TS', 'TAUX','TAUY','TAUBLJX','TAUBLJY','TAUGWX','TAUGWY','FLNT','FLNS','FSNS','FSNT',
         'LHFLX','SHFLX','TMQ','FLDS','FSDS','FSDSC','SWCF','LWCF','PRECSC','PRECSL',  'DTCOND','Z3', 'PSL'
         'PBLH','ZMDT', 'ZMDT', 'STEND_CLUBB','RVMTEND_CLUBB',
         'ZMDQ','CMFMCDZM','DPDLFLIQ','DPDLFICE','PCLDTOP','CLDTOP', 'KVH_CLUBB',
 	 'DTCORE','DQCORE','PTEQ','DCQ','QTGW','CT_H2O','DCQ','MPDQ'
fincl2 = 'TROP_T', 'TROP_P', 'Q', 'T','U850','V850','U200','V200','PRECT','PRECC','PRECL','PBLH',
         'OMEGA500','FLUT','Z500','T500','PS','PMID:I','TREFHTMN:M', 'TREFHTMX:X','TSMN:M', 'TSMX:X',
         'PBLH','ZMDT', 'ZMDT', 'STEND_CLUBB','RVMTEND_CLUBB',
         'PRECT','PRECL','U200','V200','U850','V850','FLUT','Z500','TREFHT','TS','CLDTOT','SWCF',
         'LWCF','PS','PSL','TMQ','LHFLX','SHFLX','T500','OMEGA500','CLDLOW'
fincl3 = 'U:I','V:I','T:I', 'OMEGA:I','PS:I','PMID:I', 'OMEGA500','PRECT','U200','U850','FLUT','Q:I', 'ZMDT:I','ZMDQ:I','CMFMCDZM:I','DPDLFLIQ:I','DPDLFICE:I','PCLDTOP:I','CLDTOP:I' ,
       'DTCORE:I','DQCORE:I','PTEQ:I','DCQ:I','QTGW:I','CT_H2O:I','DCQ:I','MPDQ:I'
fincl4 = 'PRECT','PRECC'
fincl8 = 'Z3:I','U850:I','V850:I','Z500:I','PS:I', 'PMID:I'

**Comment by PeterHjortLauritzen** [comment]
> @PeterHjortLauritzen
> 
> I have another question for you.
> 
> In our L58 runs, we have been using: se_rsplit = 3 se_nsplit = 2 se_hypervis_subcycle = 4
> 
> Now, we want to move to cam6_3_041. Out of the box, we get: se_rsplit = 4 se_nsplit = 5 se_hypervis_subcycle = 2
> 
> Do you want the out of the box values or the values we used in our previous L58 runs?

The out-of-the-box is for WACCM with a ~140km top that requires more stringent time-stepping (for stability) than the ~80km top model. Hence I would recommend manually setting the split values so that the model runs faster

**Comment by PeterHjortLauritzen** [comment]
> @PeterHjortLauritzen and/or @jtruesdal
> 
> In the L58, we have been using the flags: -cppdefs -Dwaccm_debug in the CAM_CONFIG_OPTS
> 
> These don't come out of the box and we have been setting these for ever. I am not even sure what they do. Do you know?
> 
> We are now moving to cam6_3_041. I am not sure we still need the flags above. I thought I would ask you.

We used this "#ifdef code" to get diagnostics for max. Courant number in each level. You don't need to set that (unless we are looking into an instability).

**Comment by adamrher** [comment]
> fincl3 = 'U:I','V:I','T:I', 'OMEGA:I','PS:I','PMID:I', 'OMEGA500','PRECT','U200','U850','FLUT','Q:I', 'ZMDT:I','ZMDQ:I','CMFMCDZM:I','DPDLFLIQ:I','DPDLFICE:I','PCLDTOP:I','CLDTOP:I' ,
'DTCORE:I','DQCORE:I','PTEQ:I','DCQ:I','QTGW:I','CT_H2O:I','DCQ:I','MPDQ:I'

You'll need to change ```CMFMCDZM``` -> ```CMFMC_DP```. Otherwise it's fine.

It would be nice to clean up these fincl's a bit. These are mere suggestions; you can take it or leave it. Make all fincl3 vars instantaneous and all fincl2 averages. Then get rid of fincl8, so you can reduce the nhtfrq array to ```nhtfrq = 0, -24, -6, -3```

**Comment by cecilehannay** [comment]
The fincl8 was on the native while the other history files were interpolated on the fly on a lat/lon grid. 

If we get rid of fincl8, I want to make sure the person who uses this is ok with the interpolated history files.  Is it you @isla?

**Comment by islasimpson** [comment]
Don't think it was me.  I don't like things on the native grid...

**Comment by adamrher** [comment]
@cecilehannay FYI, I've confirmed with Mariana that cam6_3_041 already includes the shr_flux_mod changes, so you no longer have to SourceMod those in (apologies if you already knew this).

**Comment by cecilehannay** [comment]
Thanks. I had checked that too.

The only mods I need are the ones to output the water vapor tendency due to
dycore (DQCORE)

**Comment by cecilehannay** [comment]
@PeterHjortLauritzen <https://github.com/PeterHjortLauritzen>

I will use:
se_rsplit = 3
se_nsplit = 2
se_hypervis_subcycle = 4
like in previous runs.

**Comment by swrneale** [comment]
I think ZMDT is on one fincl twice instead of ZMDQ

**Comment by cecilehannay** [comment]
This run is started as f.e21.FWscHIST.ne30_L48_BL10_cam6_3_041_control.hf.001.  
See: https://github.com/NCAR/amwg_dev/issues/53
