### ISSUE TITLE
Latest atmosphere coupled to POP

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/amwg_dev#535]
### Purpose of the run

Understand processes leading to tropical precipitation biases in CESM3

### Description of the run

This run should use the latest atmosphere, i.e., that used in exps 91 and 92, but revert the ocean model to POP.

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

SourceMods

### Sandbox

cesm2_3_alpha17f (or cesm2_3_beta17). 

### Contact info

@JulioTBacmeister @ad

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
See #542
