### ISSUE TITLE
Run w/ zm parcel depth fixed to 60 m

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#536]
**Purpose:**

Run w/ zm parcel depth fixed to 60 m

Addressing the dry slot / double-ITCZ bias. Our L32_cam6 run improved on the dry slot, and my F-case experiments indicate you can get ZM2 to mimc ZM1 by fixing the parcel depth to 60 meters.
___

**Description:**
Identical to 91 or 92 (I presume 92 based on our meetings this week), but SourceMod in a new zmconvr.F90 file here:
```
/glade/derecho/scratch/aherring/cesm2_3_alpha17f_FLTHIST_ne30pg3_ne30pg3_mg17_2432pes_240522_L32_cam6_zmparcelT_60m_Nx2yrs/SourceMods/src.cam/zm_convr.F90
```

I'm aware that run 90 is similar to what I'm proposing, but (a) this run takes the parcel depth down even more (e.g., when PBLH ~500 m), and (b) that run is on 180x360 grid and I really don't want to modify all my cesm3 scripts for that one case. I know I'm being a grump on this.
___
**Case directory:**
- Locally (if still available):
`/glade/campaign/cesm/cesmdata/cseg/runs/cesm2_0/$CASE`

- On github:
https://github.com/NCAR/amwg_dev/tree/$CASE
___
**Sandbox:**
- Locally (if still available): `/glade/work/hannay/cesm_tags/cesm2_3_alpha16g`
 
- On github: https://github.com/ESCOMP/cesm/tree/cesm2_3_alpha16g
___
**Diagnostics:**
- Diags (if available):
[https://webext.cgd.ucar.edu/BLT1850/$CASE/](https://webext.cgd.ucar.edu/BLT1850/$CASE/)
___
**Output:**
- Raw output on derecho (if still available): `/glade/derecho/scratch/hannay/archive/$CASE/`
- CAM Climos: `/glade/campaign/cgd/amp/amwg/climo/$CASE`
___
**Contacts:**
@cecilehannay @JulioTBacmeister @swrneale @PeterHjortLauritzen
___
**Extra details:**

**Comment by swrneale** [comment]
That's great to know as the parcel depth with zm is essentially the depth of the old lowest layer in L32

**Comment by cecilehannay** [comment]
Do we want to base this on 93 (i.e. using rrtmgp) as we expect this to become the default? (Of course, we don't know yet how much tuning 93 will need). 
Either way is fine with me but i thought I would ask.

**Comment by adamrher** [comment]
Let's just do 92.

**Comment by cecilehannay** [comment]
Run started as: 
https://github.com/NCAR/amwg_dev/issues/539
