### ISSUE TITLE
CLUBB interface bug fix (incorrect wet-dry mixing ratio conversions)

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/amwg_dev#545]
### Purpose of the run

Check effect of bug fix in CLUBB interface (see https://github.com/ESCOMP/CAM/issues/1053 for details).

### Description of the run

Repeat configuration 92 (https://github.com/NCAR/amwg_dev/issues/534) with bug fix

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

/glade/u/home/pel/src/for-clubb-intr-bug-fix/clubb_intr.F90

### Sandbox

Requested sandbox or tag

### Contact info

@adamrher @klindsay28 @tilmes @rgarc1a @swrneale 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
See #546 (and #547)
