### ISSUE TITLE
nuclear option w/ kzz=1 and dynamic lower boundary

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#55]
### Description of the run

Building on the run https://github.com/NCAR/amwg_dev/issues/54. The boundaries of where the diffusion is applied is changed to extend from the top of ZM plumes to 50 hPa, instead of a fixed lower boundary of 500 hPa. Diffusion is inactive if ZM is not triggered. There are no latitudinal bounds, the diffusion is applied anywhere where ZM is active.

### Namelist modifications

Same as https://github.com/NCAR/amwg_dev/issues/54, incl. DQCORE in fincl's

### Source modifications

/glade/u/home/aherring/src/cam6_3_043/usr_src/nuclopt/*
DQCORE SourceMods

### Sandbox

cam6_3_041

### Contact info

@adamrher 
@JulioTBacmeister

### Any other relevant information

configure options: -phys cam_dev -nlev 58

**Comment by cecilehannay** [comment]
Run started (https://github.com/NCAR/amwg_dev/issues/56)
