### ISSUE TITLE
ne30pg2 control

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#57]
### Description of the run

Same as https://github.com/NCAR/amwg_dev/issues/53, but using the ne30pg2_ne30pg2_mg17 grid alias. I did a test run and verified FWscHIST runs out of the box for this grid.

### Namelist modifications

Same as https://github.com/NCAR/amwg_dev/issues/53

### Source modifications

DQCORE SourceMods

### Sandbox

cam6_3_041

### Contact info

@adamrher 
@PeterHjortLauritzen 
@JulioTBacmeister 

### Any other relevant information

config opts: -phys cam_dev -nlev 58

**Comment by cecilehannay** [comment]
Run started (see: https://github.com/NCAR/amwg_dev/issues/58)
