### ISSUE TITLE
Confirm gustiness impacts in later model version

### ISSUE THREAD

**Issue by megandevlan** [NCAR/amwg_dev#573]
### Purpose of the run

Confirm the impacts of gustiness on ENSO in more recent model versions by turning off the add_gusts flag and comparing it with an otherwise identical simulation. 

### Description of the run

Identical to a recent simulation (somewhat open on choice; ideally something that seems most stable and has a fairly lengthy set of output - 098?), with the only difference being the addition of convective gustiness (add_gusts = .false. in this run). Needs to run for ~60 years for decent ENSO statistics. 

### Suffix in the casename

Suffix

### Namelist modifications

add_gusts = .false. 

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag

### Contact info

@megandevlan, @swrneale 

### Any other relevant information

Enter relevant info

**Comment by megandevlan** [comment]
Looking at some of the ENSO diags from @swrneale, I think a baseline of 104 would be really interesting for this sensitivity run with gustiness off. 104 has a pretty different ENSO relative to 098 that seems to be weaker, but I think that will work out nicely.

**Comment by cecilehannay** [comment]
This run is now running in #577
