### ISSUE TITLE
CDNUMC:New FLTHIST with 103 and 104 configuration

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/amwg_dev#581]
**Purpose:**

___

**Description:**
___
**Case directory:**
- Locally (if still available):
`/glade/campaign/cesm/cesmdata/cseg/runs/cesm2_0/$CASE`

- On github:
https://github.com/NCAR/amwg_dev/tree/$CASE
___
**Sandbox:**
- Locally (if still available):
/glade/work/hannay/cesm_tags/cam6_3_153

- On github:
https://github.com/ESCOMP/CAM/tree/cam6_3_153
___
**Diagnostics:**
- ADF diags (if available)
[https://webext.cgd.ucar.edu/FLTHIST/$CASE/atm/](https://webext.cgd.ucar.edu/FLTHIST/$CASE/atm/)
___
**Output:**
- Raw output on derecho (if still available)
`/glade/derecho/scratch/hannay/archive/$CASE/`
- CAM Climos: `/glade/campaign/cgd/amp/amwg/climo/$CASE`
___
**Contacts:**
@cecilehannay
___
**Extra details:**

**Comment by jedwards4b** [comment]
@cecilehannay In the opening description the github links for case and diagnostics include the unresolved $CASE variable - would it be better to resolve this variable for the description so that 
viewer can click the links?

**Comment by jedwards4b** [comment]
Also the /tree part of the path needs to be removed.
