### ISSUE TITLE
background Kzz increased to 3.

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/amwg_dev#59]
### Description of the run

Repeat of f.e21.FWscHIST.ne30_L48_BL10_cam6_3_041_kzz1_zmtop50.hf.001 with bkg Kzz increaed to 3 m^2/s

### Namelist modifications

none

### Source modifications

use ~juliob/run_request/advance_clubb_core_module.F90

### Sandbox

Requested sandbox or tag 

### Contact info

@JulioTBacmeister @adamrher @cecilehannay 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
Run started 
See: https://github.com/NCAR/amwg_dev/issues/60
