### ISSUE TITLE
nuclear option but w/ top lowered to 75hPa

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#77]
### Description of the run

Identical to https://github.com/NCAR/amwg_dev/issues/60, but with the top of where diffusion is applied lowered to 75hPa.

### Namelist modifications

same as https://github.com/NCAR/amwg_dev/issues/60 (hopefully you can use those DQCORE mods).

I'm thinking we try to reduce unnecessary tracers in this run but invoking:
```
./xmlchange CAM_CONFIG_OPTS='-phys cam_dev -nlev 58 -chem waccm_sc_mam4'
```
Which omits the age of air tracers. (My instinct it to overwrite cam_dev's mg3 invocation by setting -microphys mg2, but I think we should not mess with turning off graupel even though it probably don't matter, to make sure this run is apples-to-apples with the other nuclopt runs).

I'd advocate using our new trimmed history field list.

### Source modifications

SourceMods for nuclopt w/ 75hPa top is here: /glade/u/home/aherring/src/cam6_3_043/usr_src/nuclopt

### Sandbox

lets use cam6_3_041 to be consistent with https://github.com/NCAR/amwg_dev/issues/60

### Contact info

@adamrher 
@JulioTBacmeister

**Comment by cecilehannay** [comment]
> I'd advocate using our new trimmed history field list.

Here is the starting point:

```
fincl1 = 'T', 'Q', 'PS', 'PSL', 'U', 'V', 'Z3', 'OMEGA', 'CLOUD', 'QRL', 'QRS', 
'ZMDT', 'ZMDQ', 'RVMTEND_CLUBB', 'STEND_CLUBB', 'FSNT', 'FLNT', 'FLUT','FLNS', 
'FSNS', 'OMEGA500', 'PRECT', 'PRECL', 'LWCF', 'SWCF','TGCLDLWP' 
'DQCORE','PTEQ','DCQ','QTGW','CT_H2O','MPDQ','EVAPPREC','EVAPSNOW','DTCORE',
'TFIX','PTTEND','DTCOND','QRS','QRL','DTV','TTGW','MPDT','RCMTEND_CLUBB',
'MPDLIQ','MPDICE','PMID','PINT','WPTHLP_CLUBB','WPRTP_CLUBB','CLDLIQ','CLDICE'

fincl2 = 'QRS', 'QRL'

fincl3 = 'U:I', 'V:I', 'T:I', 'OMEGA:I', 'PS:I', 'PMID','Q','PRECC','PRECL'

```

Last call ! Any variable not in that list won't be output. Thanks. 

https://docs.google.com/document/d/1pMOAJ_tPL48mseFfiDaT537NwRumchM-kCp67QGLOfk/edit

**Comment by cecilehannay** [comment]
I started this run as described at:
https://github.com/NCAR/amwg_dev/issues/78
