### ISSUE TITLE
Run with no microphysics/macrophysics substepping 

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/amwg_dev#84]
### Description of the run

This run will be a repeat of https://github.com/NCAR/amwg_dev/issues/64 (cam6_3_046 with pumas microphysics)
but without doing macrophysics/microphysics substeps. 

@adamrher 
In https://github.com/NCAR/amwg_dev/issues/64, we have:
``cld_macmic_num_steps =  3``
I assume I need to set: 
``cld_macmic_num_steps =  1``
Anything else? 

@andrewgettelman (and others)
Could you confirm the fincl you want in this run. 

### Namelist modifications

```
ncdata = '/glade/p/cesm/amwg_dev/juliob/FWsc_ne30pg3_58L_GRID_48_taperstart10km_lowtop_BL10_v3_beta1p75_Top_43km.nc'
micro_mg_precip_fall_corr = .true.
se_rsplit            = 3
se_nsplit           = 2
se_hypervis_subcycle =  4
cld_macmic_num_steps =  1
```

### Source modifications

SourceMods to output Q bugdet. 

### Sandbox

cam6_3_046

### Contact info

@andrewgettelman 
@adamrher 
@julio

### Any other relevant information

Enter relevant info

**Comment by adamrher** [comment]
What is the goal of this run? If you set cld_macmic_num_steps=1, then it will run CLUBB 6 times in a row, and then will run MG micro_mg_num_steps times in a row (which defaults to 1 believe, which would be a MG time-step of 1800s --is probably unstable?).

**Comment by JulioTBacmeister** [comment]
The goal of the run is to eliminate any staggering between CLUBB and MG, so that every time CLUBB is called MG/PUMAS is called right after.  So then we should cld_macmic_num_steps=6?

**Comment by adamrher** [comment]
cld_macmic_num_steps=6 will make the time-steps used by CLUBB and MG the same; 300s. CLUBB will run once, then MG, then CLUBB, then MG, ...

But you are changing two things at once by doing this; decreasing the MG time-step and increasing the frequency that you subcycle between CLUBB and MG. I'm not sure this is what is intended for this run --shall we talk this over at 1pm?

**Comment by andrewgettelman** [comment]
I'm once again totally lost with the sub-stepping. I think that needs to be modified as well. I think I'm doing it all wrong in my SCAM simulations. I'm probably going to propose we try to rewrite the code to rationalize the substepping. Every time I look it confuses me. 

The goal is yes, to make the sub-steps the same so we are only calling MG once every time we call CLUBB. 

I'd like to join at 1p but have a meeting 1-1:30p. But I'm definitely going to need some help on this.

**Comment by JulioTBacmeister** [comment]
My take is that the goal is to establish a baseline for exploring the time step sensitivity of the cloud physics in the model. It's better to do this without the confusion of different PUMAS and CLUBB call frequency per timestep

**Comment by adamrher** [comment]
i think cld_macmic_num_steps = 6 and micro_mg_num_steps=1, is the "practical" baseline. The "unpractical" baseline might be micro_mg_num_steps = 8 (as advocated by Jiang, Sean and others).

**Comment by andrewgettelman** [comment]
Agreed. 

What does micro_mg_num_steps = 8 do again? 

How would we start sub cycling the microphysics under CLUBB with a 300s timestep (e.g. 150s microphysics timestep, 2 substeps)? is that cld_macmic_num_steps = 6 and micro_mg_num_steps=2 ?

**Comment by adamrher** [comment]
for default micro_mg_num_steps = 1, then dt_mg = 1800/cld_macmic_num_steps
for micro_mg_num_steps = 2, then dt_mg = 1800/cld_macmic_num_steps/2
...
for micro_mg_num_steps = 8, then dt_mg = 1800/cld_macmic_num_steps/8

SCAM is different for ... reasons (leap frog time-stepping in EUL dycore means the physics time-step is 2X larger than that determined by ATM_NCPL). We can talk about that ...

**Comment by andrewgettelman** [comment]
We need to talk about that.... I don't think I am running what I think I am running then.

**Comment by cecilehannay** [comment]
Are you discussing this in your 1pm?

**Comment by adamrher** [comment]
I think we are going to table this run after talking this over w/ Julio and Andrew. Julio may want to run w/ ATM_NCPL=288 and cld_macmic_num_steps=1. That would require setting se_nsplit=1,se_rsplit=1 as well (so as to not run w/ unnecessarily small dyn time steps). However, I think Andrew already planned on doing this? I dunno.

**Comment by andrewgettelman** [comment]
I'm going to do it in SCAM. I think we were going to see what happens there first.

**Comment by adamrher** [comment]
this thread can be deleted, as it is picked up in https://github.com/NCAR/amwg_dev/issues/87

**Comment by cecilehannay** [comment]
See: https://github.com/NCAR/amwg_dev/issues/87
