### ISSUE TITLE
L58, no physics subcycling

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/amwg_dev#87]
### Description of the run

Physics without CLUBB/ microphysics subcycling at a physics time step of 300 seconds.  Using "pre-PUMAS" L58 model.

### Namelist modifications

ATM_NCPL==> 288 
cld_macmic_num_steps ==> 1

Peter Lauritzen should comment on dycore time step settings

### Source modifications

SourceMods

### Sandbox

Requested sandbox or tag 

### Contact info

Julio Bacmeister

### Any other relevant information

Enter relevant info

**Comment by adamrher** [comment]
> Peter Lauritzen should comment on dycore time step settings

we just need to set se_nsplit=1 & se_rsplit=1. @PeterHjortLauritzen since this means there is only one remap cycle, then all the ftype's are the same in this case, right? I.e., the full physics tracer increment will be dumped into the first subcycle?

@cecilehannay to be save set the wall time to 288/48 ~ 6x times larger. It will probably be closer to 3-4X more expensive though b/c clubb is running at the same time-step.

**Comment by adamrher** [comment]
I would also request one last convo between @JulioTBacmeister and I before submitting this.

**Comment by PeterHjortLauritzen** [comment]
looks good if se_nsplit=6 (are we running ~80km top where we modified the split variables "manually"?). The se_hypervis_* variables can also be reduced if they are not already 1.

**Comment by adamrher** [comment]
> looks good if se_nsplit=6 (are we running ~80km top where we modified the split variables "manually"?)

I'm confused, where is se_nsplit=6 coming from? We're running 40km L58. And setting ATM_NCPL=288, and se_nsplit=1 and se_rsplit=1.

**Comment by JulioTBacmeister** [comment]
Yes, I'm requesting an L58 run, so top around 40km not 80,

**Comment by adamrher** [comment]
@JulioTBacmeister and I have spoken and we're giving the green light for this run. Just looking for clarification from @PeterHjortLauritzen on his se_nsplit=6 comment, and I think we're good to go. (Peter dt_dyn_vis needs ~100 s time-step according a ne30pg3 run I'm looking at ... so the default se_hypervisc_subcycle=3 default should probably stay?)

And to be clear this run should be identical to https://github.com/NCAR/amwg_dev/issues/53 other then the time-stepping (ATM_NCPL=288, cld_macmic_num_steps=1,se_nsplit=1,se_rsplit=1)

**Comment by PeterHjortLauritzen** [comment]
Standard ~40km setup uses the following split variables: 

se_nsplit              = 2
se_rsplit              = 3
se_hypervis_subcycle           = 3

resulting in the following time-steps for vertical remap, dynamics and viscosity: 

dt_remap=900s
dt_dyn=300s
dt_vis=100s.

If we set:

se_nsplit              = 1
se_rsplit              = 1
se_hypervis_subcycle = 3

with a 5 minutes physics time-step we get:

dt_remap=300s
dt_dyn=300s
dt_vis=100s.
 
So yes @adamrher you are correct (this choice should be stable). (with the ~80km top we increased se_nsplit so the time-steps would be different).

**Comment by cecilehannay** [comment]
See also: https://github.com/NCAR/amwg_dev/issues/92
