### ISSUE TITLE
first clubb dribbling run

### ISSUE THREAD

**Issue by adamrher** [NCAR/amwg_dev#88]
### Description of the run

Identical to https://github.com/NCAR/amwg_dev/issues/53, but w/ dribbling of dynamics into CLUBB/MG2 subcycle, and cld_macmic_num_steps=6.

### Namelist modifications

cld_macmic_num_steps=6
l_dribble_tend_into_macmic_loop = .true.
dribble_start_step = 2

### Source modifications

DQCORE -- I will instead push them into the cam.dribble branch so we don't need SourceMods. I'll respond to this thread when the code is ready to be checked out.

### Sandbox

please run my dribbling branch:

git checkout https://github.com/adamrher/CAM.git cam6_3_041.dribble
cd cam6_3_041.dribble
git checkout cam.dribble
./manage_externals/checkout_externals

### Contact info

@adamrher 
@JulioTBacmeister 

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
Run started: https://github.com/NCAR/amwg_dev/issues/91
