### ISSUE TITLE
dt=150 seconds

### ISSUE THREAD

**Issue by JulioTBacmeister** [NCAR/amwg_dev#94]
### Description of the run

Like 'nosubcycle' except with a time-step of 150 secs, i.e., atm_ncpl = 576.  Purpose: To evaluate convergence of physics w/resp to time-step. 

Should be short run: 3 years

### Namelist modifications

Namelist

### Source modifications

ATM_NCPL=576, ... macmic... =1

### Sandbox

Same as for 'nosubcycle'

### Contact info

julio bacmeister

### Any other relevant information

Short run - 3 years.

**Comment by adamrher** [comment]
you know me, I like DQCORE. 

Also, lets start outputting detailed timings for these physics time-step sensitivity runs. Set:
 ```
./xmlchange TIMER_LEVEL=10
```

**Comment by adamrher** [comment]
To be explicit, the dycore time-stepping ("splits") should be the same as in https://github.com/NCAR/amwg_dev/issues/92, but you can lower:
 ```
se_hypervis_subcycle = 3->2
```

Since that gives 75s (the default is to use 100 s for hypervisc time-stepping).

**Comment by cecilehannay** [comment]
@adamrher: 
> you know me, I like DQCORE.

I was not even thinking of not outputting it. If I was output only one variable, it would be DQCORE. ;)

**Comment by cecilehannay** [comment]
run started: #95
