### ISSUE TITLE
Test topo mods for SE (two configurations)

### ISSUE THREAD

**Issue by PeterHjortLauritzen** [NCAR/amwg_dev#96]
### Description of the run

Two separate 10 year runs to assess impact of modifications to SE to alleviate numerical noise near topography:

Modification 1 for physics grid:

- Map PHIS from GLL grid to physics grid to alleviate noise in derived fields such as PSL and eddy Z500 (see https://github.com/ESCOMP/CAM/issues/552)

Two additional candidate modifications:

1. Exner function formulation of pressure gradient force (PGF) (see Figure (c) in plots below)
2. Exner function formulation of pressure gradient force (PGF) + subtract reference profiles from T and dp before applying hyperviscosity (see Figure (d) in plots below).

Justification provided in these Figures (OMEGA500 and PRECT for 1 year CAM6 runs using 32 vertical levels; i.e. cam_development F2000climo compset out of the box):

[OMEGA.pdf](https://github.com/NCAR/amwg_dev/files/8422868/OMEGA.pdf)
[PRECT.pdf](https://github.com/NCAR/amwg_dev/files/8422870/PRECT.pdf)

Revisiting this issue it was found that changing to the Exner function formulation of the pressure gradient force leads to the largest improvements in terms of topo noise (compare Figure a, CAM-FV, with Figure b, CAM-SE with old PGF formulation used in CESM2.0, and c described in item 1 above). In addition to Exner PGF, if one also subtracts reference profiles for T and dp (see Figure d) it seems to lead to some improvement over very steep topography (e.g. Southern Andes) but the OMEGA500 field looks less similar to FV over, e.g., the Rockies (compare a, c and d). 

We would like to check in the high vertical resolution configuration which of these two configurations are preferable.

The correction for temperature viscosity on approximate pressure levels seems very detrimental (see Figures e and f). Unfortunately (e) is was we have been using in the latest development runs. Version (d) is what was released with CESM2.2

### Suffix in the casename

Suffix

### Namelist modifications

Namelist

### Source modifications

Source mods for configuration 1:

/glade/u/home/pel/src/for-cecille/topo-mods1

Source mods for configuration 2:

/glade/u/home/pel/src/for-cecille/topo-mods2

### Sandbox

cam6_3_041 (the configuration we are going to use for the initial MOM6 coupled runs)

### Contact info

Peter Hjort Lauritzen
Adam Herrington
Julio Bacmeister

### Any other relevant information

Enter relevant info

**Comment by adamrher** [comment]
These runs should be identical to https://github.com/NCAR/amwg_dev/issues/53 otherwise. I would like to add a history tape on the native se-grid to have 6-hourly instantaneous FT_gll (physics T tendency on GLL grid) and OMEGA500.

**Comment by cecilehannay** [comment]
Sounds good. I will output these on the native grid.
The run is ready to start.
If you want to check that you have everything you need:
/glade/p/cesmdata/cseg/runs/cesm2_0/f.c6_3_41.FWscHIST.ne30_L58_exner.001
