### ISSUE TITLE
Bug fix and cleanup of ZM2 mods

### ISSUE THREAD

**Issue by swrneale** [NCAR/amwg_dev#99]
### Description of the run

Includes a fix to prevent division by zero identified in ESCOMP/CAM issue #543. Also includes some clean up of the definition of PBL height and ZM2 mixing height.

### Suffix in the casename

zm2_fix ?

### Namelist modifications

None - Should be current default L58 with ZM2.

### Source modifications

https://github.com/swrneale/CAM/blob/cam6_parcel_zm/src/physics/cam/zm_conv.F90

### Sandbox

https://github.com/swrneale/CAM/blob/cam6_parcel_zm

### Contact info

Rich Neale (rneale@ucar.edu)

### Any other relevant information

Enter relevant info

**Comment by cecilehannay** [comment]
run started (#100)
